use('VentasMotos');

db.Motos.insertMany(
    [{ "marca": "Motos Yamaha", "modelo": "Classic", "cilindraje": 936, "color": ["Marrón"], "Combustible": "extra", "placa": "345MNO", "precio": 10966904 },
    { "marca": "Auteco", "modelo": "Africa Twin", "cilindraje": 292, "color": ["gris", "blanco", "plateado"], "Combustible": "extra", "placa": "LMN456", "precio": 17987389 },
    { "marca": "TVS", "modelo": "Xpulse", "cilindraje": 724, "color": ["Marrón", "negro", "gris"], "Combustible": "corriente", "placa": "ABC123", "precio": 8360485 },
    { "marca": "AKT", "modelo": "fz25", "cilindraje": 287, "color": ["naranja"], "Combustible": "super", "placa": "345MNO", "precio": 13810175 },
    { "marca": "Motos Yamaha", "modelo": "Ntorq", "cilindraje": 286, "color": ["rojo y azul", "Turquesa"], "Combustible": "corriente", "placa": "ZAB234", "precio": 7194889 },
    { "marca": "Royal Enfield", "modelo": "Classic", "cilindraje": 335, "color": ["negro", "naranja", "blanco"], "Combustible": "corriente", "placa": "HIJ456", "precio": 8055645 },
    { "marca": "Royal Enfield", "modelo": "Ntorq", "cilindraje": 560, "color": ["amarillo"], "Combustible": "super", "placa": "LMN456", "precio": 14182944 },
    { "marca": "Motos Honda", "modelo": "CB 125", "cilindraje": 137, "color": ["naranja", "plateado"], "Combustible": "extra", "placa": "DEF456", "precio": 7929891 },
    { "marca": "Motos Yamaha", "modelo": "NMAX", "cilindraje": 228, "color": ["plateado", "rojo y azul"], "Combustible": "extra", "placa": "123EFG", "precio": 10812966 },
    { "marca": "AKT", "modelo": "25 NKD", "cilindraje": 745, "color": ["blanco", "plateado"], "Combustible": "extra", "placa": "789KLM", "precio": 12011477 },
    { "marca": "Hero", "modelo": "YZF-R", "cilindraje": 806, "color": ["plateado"], "Combustible": "extra", "placa": "TUV678", "precio": 18014648 },
    { "marca": "Auteco", "modelo": "Ntorq", "cilindraje": 932, "color": ["naranja"], "Combustible": "corriente", "placa": "234ZAB", "precio": 10277801 },
    { "marca": "Royal Enfield", "modelo": "Intercept", "cilindraje": 579, "color": ["plateado"], "Combustible": "super", "placa": "890FGH", "precio": 14065177 },
    { "marca": "Motos Honda", "modelo": "Apache", "cilindraje": 562, "color": ["plateado", "negro"], "Combustible": "super", "placa": "HIJ456", "precio": 5074151 },
    { "marca": "AKT", "modelo": "Dominar", "cilindraje": 645, "color": ["negro"], "Combustible": "super", "placa": "NOP012", "precio": 6229958 },
    { "marca": "Royal Enfield", "modelo": "Africa Twin", "cilindraje": 696, "color": ["blanco", "Marrón"], "Combustible": "corriente", "placa": "HIJ456", "precio": 11206412 },
    { "marca": "TVS", "modelo": "Pulsar", "cilindraje": 726, "color": ["verde", "naranja"], "Combustible": "super", "placa": "QRS345", "precio": 19071382 },
    { "marca": "TVS", "modelo": "Pulsar", "cilindraje": 951, "color": ["Marrón", "amarillo", "naranja"], "Combustible": "corriente", "placa": "UVW345", "precio": 11070316 },
    { "marca": "Motos Suzuki", "modelo": "250 Adventure", "cilindraje": 952, "color": ["verde", "blanco", "plateado"], "Combustible": "super", "placa": "678TUV", "precio": 13063835 },
    { "marca": "TVS", "modelo": "Pulsar", "cilindraje": 435, "color": ["verde"], "Combustible": "corriente", "placa": "345QRS", "precio": 9663349 },
    { "marca": "TVS", "modelo": "GSX-R", "cilindraje": 677, "color": ["blanco", "rojo y azul", "amarillo"], "Combustible": "corriente", "placa": "XYZ678", "precio": 8943933 },
    { "marca": "Motos Honda", "modelo": "GSX-R", "cilindraje": 958, "color": ["verde"], "Combustible": "corriente", "placa": "901STU", "precio": 7679310 },
    { "marca": "Auteco", "modelo": "Africa Twin", "cilindraje": 357, "color": ["blanco", "gris", "Marrón"], "Combustible": "super", "placa": "DEF456", "precio": 17337243 },
    { "marca": "Royal Enfield", "modelo": "Classic", "cilindraje": 801, "color": ["naranja", "negro"], "Combustible": "super", "placa": "123IJK", "precio": 10714941 },
    { "marca": "Royal Enfield", "modelo": "250 Adventure", "cilindraje": 991, "color": ["negro", "rojo y azul"], "Combustible": "corriente", "placa": "MNO345", "precio": 10422087 },
    { "marca": "Hero", "modelo": "Intercept", "cilindraje": 440, "color": ["plateado"], "Combustible": "extra", "placa": "RST012", "precio": 16470276 },
    { "marca": "Royal Enfield", "modelo": "Splendor", "cilindraje": 190, "color": ["verde", "Turquesa", "negro"], "Combustible": "super", "placa": "HIJ456", "precio": 12152060 },
    { "marca": "AKT", "modelo": "Pulsar", "cilindraje": 204, "color": ["negro", "naranja", "Marrón"], "Combustible": "extra", "placa": "234VWX", "precio": 9310615 },
    { "marca": "Royal Enfield", "modelo": "250 Adventure", "cilindraje": 400, "color": ["gris"], "Combustible": "extra", "placa": "NOP012", "precio": 19843253 },
    { "marca": "AKT", "modelo": "fz25", "cilindraje": 556, "color": ["negro", "gris"], "Combustible": "super", "placa": "YZA567", "precio": 18239331 },
    { "marca": "Auteco", "modelo": "Classic", "cilindraje": 988, "color": ["naranja", "gris", "verde"], "Combustible": "extra", "placa": "WXY901", "precio": 14603551 },
    { "marca": "Motos Honda", "modelo": "CBR", "cilindraje": 454, "color": ["verde", "Turquesa", "Marrón"], "Combustible": "extra", "placa": "456HIJ", "precio": 17791587 },
    { "marca": "Hero", "modelo": "Intercept", "cilindraje": 637, "color": ["rojo y azul", "negro", "Marrón"], "Combustible": "super", "placa": "789OPQ", "precio": 17659978 },
    { "marca": "Motos Suzuki", "modelo": "YZF-R", "cilindraje": 158, "color": ["naranja"], "Combustible": "extra", "placa": "XYZ678", "precio": 17389717 },
    { "marca": "Auteco", "modelo": "25 NKD", "cilindraje": 848, "color": ["plateado"], "Combustible": "extra", "placa": "345QRS", "precio": 12020370 },
    { "marca": "Motos Suzuki", "modelo": "YZF-R", "cilindraje": 614, "color": ["naranja", "Marrón"], "Combustible": "extra", "placa": "678PQR", "precio": 19976806 },
    { "marca": "AKT", "modelo": "Splendor", "cilindraje": 789, "color": ["Turquesa", "amarillo", "plateado"], "Combustible": "super", "placa": "234VWX", "precio": 5022817 },
    { "marca": "Motos Honda", "modelo": "Agility", "cilindraje": 736, "color": ["negro", "rojo y azul"], "Combustible": "corriente", "placa": "QRS345", "precio": 17153705 },
    { "marca": "TVS", "modelo": "Xpulse", "cilindraje": 773, "color": ["gris"], "Combustible": "corriente", "placa": "012RST", "precio": 5493914 },
    { "marca": "AKT", "modelo": "CB 125", "cilindraje": 781, "color": ["plateado", "blanco"], "Combustible": "super", "placa": "KLM789", "precio": 19442694 },
    { "marca": "Motos Yamaha", "modelo": "Apache", "cilindraje": 185, "color": ["naranja", "rojo y azul", "blanco"], "Combustible": "corriente", "placa": "OPQ789", "precio": 19685704 },
    { "marca": "AKT", "modelo": "-Strom", "cilindraje": 502, "color": ["blanco", "rojo y azul", "Turquesa"], "Combustible": "super", "placa": "RST012", "precio": 12356570 },
    { "marca": "Motos Yamaha", "modelo": "Africa Twin", "cilindraje": 274, "color": ["blanco", "negro"], "Combustible": "super", "placa": "IJK123", "precio": 12547919 },
    { "marca": "Motos Suzuki", "modelo": "fz25", "cilindraje": 266, "color": ["Marrón"], "Combustible": "super", "placa": "901WXY", "precio": 13282817 },
    { "marca": "Auteco", "modelo": "Ntorq", "cilindraje": 539, "color": ["rojo y azul"], "Combustible": "corriente", "placa": "WXY901", "precio": 13536480 },
    { "marca": "Motos Honda", "modelo": "Dominar", "cilindraje": 833, "color": ["amarillo", "rojo y azul", "plateado"], "Combustible": "corriente", "placa": "234ZAB", "precio": 14487138 },
    { "marca": "Motos Suzuki", "modelo": "YZF-R", "cilindraje": 715, "color": ["rojo y azul", "negro", "blanco"], "Combustible": "extra", "placa": "OPQ789", "precio": 18324489 },
    { "marca": "AKT", "modelo": "Dominar", "cilindraje": 369, "color": ["naranja", "Turquesa", "blanco"], "Combustible": "super", "placa": "345QRS", "precio": 10301339 },
    { "marca": "Royal Enfield", "modelo": "NMAX", "cilindraje": 398, "color": ["naranja"], "Combustible": "super", "placa": "234VWX", "precio": 7630172 },
    { "marca": "Auteco", "modelo": "Splendor", "cilindraje": 557, "color": ["plateado"], "Combustible": "extra", "placa": "FGH890", "precio": 11345178 },
    { "marca": "Royal Enfield", "modelo": "NMAX", "cilindraje": 142, "color": ["naranja", "amarillo"], "Combustible": "super", "placa": "KLM789", "precio": 12877499 },
    { "marca": "AKT", "modelo": "Xpulse", "cilindraje": 608, "color": ["Marrón", "negro", "gris"], "Combustible": "extra", "placa": "123IJK", "precio": 5347799 },
    { "marca": "Auteco", "modelo": "Africa Twin", "cilindraje": 395, "color": ["Marrón"], "Combustible": "corriente", "placa": "901STU", "precio": 17895614 },
    { "marca": "Motos Suzuki", "modelo": "Apache", "cilindraje": 883, "color": ["negro", "amarillo", "plateado"], "Combustible": "corriente", "placa": "123IJK", "precio": 8519483 },
    { "marca": "Hero", "modelo": "fz25", "cilindraje": 838, "color": ["plateado", "blanco", "gris"], "Combustible": "extra", "placa": "890FGH", "precio": 9103559 },
    { "marca": "TVS", "modelo": "Xpulse", "cilindraje": 502, "color": ["verde"], "Combustible": "extra", "placa": "567YZA", "precio": 19428332 },
    { "marca": "AKT", "modelo": "GSX-R", "cilindraje": 356, "color": ["plateado"], "Combustible": "extra", "placa": "789OPQ", "precio": 8714854 },
    { "marca": "TVS", "modelo": "GSX-R", "cilindraje": 595, "color": ["gris"], "Combustible": "extra", "placa": "GHI789", "precio": 9258449 },
    { "marca": "Motos Suzuki", "modelo": "Agility", "cilindraje": 767, "color": ["amarillo"], "Combustible": "corriente", "placa": "123IJK", "precio": 4508366 },
    { "marca": "AKT", "modelo": "fz25", "cilindraje": 853, "color": ["Marrón", "naranja"], "Combustible": "corriente", "placa": "012NOP", "precio": 5371259 },
    { "marca": "Motos Yamaha", "modelo": "Pulsar", "cilindraje": 702, "color": ["verde"], "Combustible": "super", "placa": "456HIJ", "precio": 7406767 },
    { "marca": "TVS", "modelo": "CB 125", "cilindraje": 104, "color": ["verde", "negro", "plateado"], "Combustible": "corriente", "placa": "ABC123", "precio": 19009373 },
    { "marca": "Motos Honda", "modelo": "Apache", "cilindraje": 213, "color": ["gris", "naranja", "rojo y azul"], "Combustible": "super", "placa": "567CDE", "precio": 5297453 },
    { "marca": "Motos Suzuki", "modelo": "Africa Twin", "cilindraje": 350, "color": ["verde", "negro"], "Combustible": "extra", "placa": "GHI789", "precio": 8379606 },
    { "marca": "Motos Suzuki", "modelo": "Apache", "cilindraje": 929, "color": ["gris", "negro", "amarillo"], "Combustible": "corriente", "placa": "345MNO", "precio": 15080098 },
    { "marca": "TVS", "modelo": "Pulsar", "cilindraje": 260, "color": ["Turquesa"], "Combustible": "extra", "placa": "567YZA", "precio": 19288639 },
    { "marca": "AKT", "modelo": "Xpulse", "cilindraje": 700, "color": ["gris"], "Combustible": "extra", "placa": "789GHI", "precio": 5804561 },
    { "marca": "Hero", "modelo": "Xpulse", "cilindraje": 902, "color": ["verde", "rojo y azul"], "Combustible": "corriente", "placa": "123EFG", "precio": 7139924 },
    { "marca": "Hero", "modelo": "Ntorq", "cilindraje": 250, "color": ["blanco", "verde", "naranja"], "Combustible": "extra", "placa": "EFG123", "precio": 15892845 },
    { "marca": "Motos Suzuki", "modelo": "GSX-R", "cilindraje": 605, "color": ["Turquesa", "amarillo", "naranja"], "Combustible": "super", "placa": "567CDE", "precio": 15336335 },
    { "marca": "Royal Enfield", "modelo": "250 Adventure", "cilindraje": 668, "color": ["negro", "Turquesa"], "Combustible": "super", "placa": "ZAB234", "precio": 10308120 },
    { "marca": "Auteco", "modelo": "Agility", "cilindraje": 324, "color": ["blanco"], "Combustible": "corriente", "placa": "789OPQ", "precio": 8949134 },
    { "marca": "Motos Honda", "modelo": "Agility", "cilindraje": 950, "color": ["negro"], "Combustible": "extra", "placa": "YZA567", "precio": 9287486 },
    { "marca": "Auteco", "modelo": "Apache", "cilindraje": 822, "color": ["rojo y azul", "blanco"], "Combustible": "extra", "placa": "123EFG", "precio": 13342996 },
    { "marca": "Auteco", "modelo": "Intercept", "cilindraje": 993, "color": ["rojo y azul", "negro", "gris"], "Combustible": "extra", "placa": "EFG123", "precio": 14161401 },
    { "marca": "Hero", "modelo": "Ntorq", "cilindraje": 538, "color": ["naranja", "Marrón", "negro"], "Combustible": "extra", "placa": "789KLM", "precio": 15557487 },
    { "marca": "Royal Enfield", "modelo": "Intercept", "cilindraje": 297, "color": ["Marrón", "Turquesa", "blanco"], "Combustible": "corriente", "placa": "901STU", "precio": 14916145 },
    { "marca": "Auteco", "modelo": "GSX-R", "cilindraje": 191, "color": ["Turquesa"], "Combustible": "corriente", "placa": "789KLM", "precio": 14380588 },
    { "marca": "TVS", "modelo": "CB 125", "cilindraje": 835, "color": ["verde", "Marrón", "blanco"], "Combustible": "corriente", "placa": "OPQ789", "precio": 8859453 },
    { "marca": "TVS", "modelo": "CBR", "cilindraje": 356, "color": ["verde", "Marrón"], "Combustible": "super", "placa": "GHI789", "precio": 18971236 },
    { "marca": "Motos Yamaha", "modelo": "CBR", "cilindraje": 876, "color": ["negro", "Turquesa", "naranja"], "Combustible": "extra", "placa": "345QRS", "precio": 7201587 },
    { "marca": "Motos Suzuki", "modelo": "Intercept", "cilindraje": 822, "color": ["Turquesa"], "Combustible": "corriente", "placa": "012RST", "precio": 12631074 },
    { "marca": "Motos Suzuki", "modelo": "Africa Twin", "cilindraje": 585, "color": ["Marrón"], "Combustible": "extra", "placa": "XYZ678", "precio": 6770912 },
    { "marca": "Motos Yamaha", "modelo": "Pulsar", "cilindraje": 224, "color": ["rojo y azul", "blanco", "verde"], "Combustible": "corriente", "placa": "VWX234", "precio": 9741775 },
    { "marca": "Royal Enfield", "modelo": "-Strom", "cilindraje": 990, "color": ["Turquesa", "verde", "rojo y azul"], "Combustible": "corriente", "placa": "901STU", "precio": 5652261 },
    { "marca": "TVS", "modelo": "fz25", "cilindraje": 547, "color": ["Marrón", "blanco", "gris"], "Combustible": "corriente", "placa": "RST012", "precio": 18136177 },
    { "marca": "TVS", "modelo": "Classic", "cilindraje": 969, "color": ["verde"], "Combustible": "super", "placa": "ZAB234", "precio": 13022361 },
    { "marca": "Motos Yamaha", "modelo": "Ntorq", "cilindraje": 568, "color": ["rojo y azul", "gris", "naranja"], "Combustible": "corriente", "placa": "VWX234", "precio": 12889698 },
    { "marca": "AKT", "modelo": "Intercept", "cilindraje": 748, "color": ["negro", "blanco", "Marrón"], "Combustible": "super", "placa": "OPQ789", "precio": 16648417 },
    { "marca": "Auteco", "modelo": "Apache", "cilindraje": 927, "color": ["blanco", "rojo y azul"], "Combustible": "super", "placa": "HIJ456", "precio": 6650098 },
    { "marca": "TVS", "modelo": "YZF-R", "cilindraje": 793, "color": ["rojo y azul"], "Combustible": "extra", "placa": "ZAB234", "precio": 15773407 },
    { "marca": "Auteco", "modelo": "CBR", "cilindraje": 971, "color": ["Marrón", "negro", "Turquesa"], "Combustible": "extra", "placa": "456LMN", "precio": 5170131 },
    { "marca": "AKT", "modelo": "CBR", "cilindraje": 899, "color": ["plateado", "verde"], "Combustible": "extra", "placa": "123ABC", "precio": 7065107 },
    { "marca": "Auteco", "modelo": "Ntorq", "cilindraje": 464, "color": ["naranja", "blanco", "amarillo"], "Combustible": "corriente", "placa": "567YZA", "precio": 13156863 },
    { "marca": "Auteco", "modelo": "Splendor", "cilindraje": 712, "color": ["blanco", "gris"], "Combustible": "super", "placa": "567YZA", "precio": 17148121 },
    { "marca": "Motos Honda", "modelo": "Intercept", "cilindraje": 891, "color": ["Marrón", "amarillo", "verde"], "Combustible": "corriente", "placa": "OPQ789", "precio": 12470753 },
    { "marca": "Royal Enfield", "modelo": "-Strom", "cilindraje": 407, "color": ["negro", "gris", "blanco"], "Combustible": "corriente", "placa": "WXY901", "precio": 8890088 },
    { "marca": "Auteco", "modelo": "250 Adventure", "cilindraje": 647, "color": ["amarillo", "rojo y azul"], "Combustible": "super", "placa": "901WXY", "precio": 19377954 },
    { "marca": "Royal Enfield", "modelo": "Intercept", "cilindraje": 648, "color": ["blanco"], "Combustible": "corriente", "placa": "NOP012", "precio": 9451253 },
    { "marca": "Motos Yamaha", "modelo": "250 Adventure", "cilindraje": 715, "color": ["Marrón", "plateado", "amarillo"], "Combustible": "super", "placa": "LMN456", "precio": 6073972 },
    { "marca": "Auteco", "modelo": "NMAX", "cilindraje": 778, "color": ["Turquesa", "naranja", "plateado"], "Combustible": "super", "placa": "KLM789", "precio": 6974437 },
    { "marca": "Motos Suzuki", "modelo": "250 Adventure", "cilindraje": 567, "color": ["plateado", "Turquesa", "naranja"], "Combustible": "super", "placa": "456HIJ", "precio": 16645718 },
    { "marca": "Hero", "modelo": "YZF-R", "cilindraje": 841, "color": ["plateado", "Turquesa", "naranja"], "Combustible": "super", "placa": "HIJ456", "precio": 14133438 },
    { "marca": "Motos Suzuki", "modelo": "-Strom", "cilindraje": 943, "color": ["verde"], "Combustible": "corriente", "placa": "123EFG", "precio": 12629114 },
    { "marca": "Auteco", "modelo": "Xpulse", "cilindraje": 181, "color": ["amarillo"], "Combustible": "extra", "placa": "ABC123", "precio": 15333351 },
    { "marca": "Motos Yamaha", "modelo": "Intercept", "cilindraje": 590, "color": ["Turquesa", "verde"], "Combustible": "corriente", "placa": "PQR678", "precio": 10587533 },
    { "marca": "AKT", "modelo": "CB 125", "cilindraje": 715, "color": ["blanco", "amarillo", "naranja"], "Combustible": "super", "placa": "ZAB234", "precio": 5214547 },
    { "marca": "AKT", "modelo": "Agility", "cilindraje": 483, "color": ["negro", "blanco"], "Combustible": "super", "placa": "WXY901", "precio": 17975427 },
    { "marca": "Motos Suzuki", "modelo": "Ntorq", "cilindraje": 833, "color": ["negro", "blanco", "gris"], "Combustible": "super", "placa": "QRS345", "precio": 8220375 },
    { "marca": "Auteco", "modelo": "Xpulse", "cilindraje": 908, "color": ["naranja", "blanco", "Marrón"], "Combustible": "extra", "placa": "234ZAB", "precio": 11388385 },
    { "marca": "Motos Suzuki", "modelo": "Agility", "cilindraje": 321, "color": ["gris", "Turquesa", "plateado"], "Combustible": "corriente", "placa": "345QRS", "precio": 19071531 },
    { "marca": "Auteco", "modelo": "Ntorq", "cilindraje": 426, "color": ["Turquesa", "verde", "amarillo"], "Combustible": "extra", "placa": "XYZ678", "precio": 6308719 },
    { "marca": "AKT", "modelo": "Dominar", "cilindraje": 189, "color": ["verde"], "Combustible": "extra", "placa": "PQR678", "precio": 10974472 },
    { "marca": "TVS", "modelo": "Dominar", "cilindraje": 928, "color": ["plateado", "Marrón"], "Combustible": "extra", "placa": "PQR678", "precio": 4970922 },
    { "marca": "Auteco", "modelo": "fz25", "cilindraje": 782, "color": ["blanco", "plateado"], "Combustible": "super", "placa": "STU901", "precio": 13806374 },
    { "marca": "Motos Suzuki", "modelo": "GSX-R", "cilindraje": 335, "color": ["gris", "verde"], "Combustible": "super", "placa": "MNO345", "precio": 7424846 },
    { "marca": "AKT", "modelo": "CBR", "cilindraje": 694, "color": ["naranja", "blanco", "verde"], "Combustible": "extra", "placa": "123IJK", "precio": 8947814 },
    { "marca": "Motos Suzuki", "modelo": "CBR", "cilindraje": 995, "color": ["rojo y azul", "Marrón"], "Combustible": "super", "placa": "ABC123", "precio": 10749601 },
    { "marca": "Motos Suzuki", "modelo": "Dominar", "cilindraje": 157, "color": ["verde", "rojo y azul", "naranja"], "Combustible": "super", "placa": "123EFG", "precio": 18004478 },
    { "marca": "AKT", "modelo": "Classic", "cilindraje": 209, "color": ["blanco", "Turquesa", "negro"], "Combustible": "super", "placa": "234VWX", "precio": 8065423 },
    { "marca": "TVS", "modelo": "Pulsar", "cilindraje": 605, "color": ["gris", "verde"], "Combustible": "super", "placa": "RST012", "precio": 12967477 },
    { "marca": "Auteco", "modelo": "NMAX", "cilindraje": 340, "color": ["blanco", "verde", "negro"], "Combustible": "extra", "placa": "678PQR", "precio": 9518198 },
    { "marca": "Motos Yamaha", "modelo": "Intercept", "cilindraje": 362, "color": ["naranja", "gris", "plateado"], "Combustible": "corriente", "placa": "123EFG", "precio": 11020313 },
    { "marca": "AKT", "modelo": "GSX-R", "cilindraje": 337, "color": ["gris"], "Combustible": "corriente", "placa": "123EFG", "precio": 9328092 },
    { "marca": "Hero", "modelo": "Classic", "cilindraje": 348, "color": ["naranja", "amarillo", "plateado"], "Combustible": "corriente", "placa": "012JKL", "precio": 8656215 },
    { "marca": "Motos Honda", "modelo": "GSX-R", "cilindraje": 617, "color": ["naranja", "Marrón", "plateado"], "Combustible": "extra", "placa": "IJK123", "precio": 14906593 },
    { "marca": "Motos Suzuki", "modelo": "Splendor", "cilindraje": 355, "color": ["Turquesa", "naranja", "verde"], "Combustible": "extra", "placa": "890FGH", "precio": 15226498 },
    { "marca": "Motos Yamaha", "modelo": "Dominar", "cilindraje": 214, "color": ["blanco"], "Combustible": "super", "placa": "EFG123", "precio": 10013533 },
    { "marca": "Motos Honda", "modelo": "Pulsar", "cilindraje": 721, "color": ["verde", "naranja", "plateado"], "Combustible": "extra", "placa": "ZAB234", "precio": 13160890 },
    { "marca": "Motos Yamaha", "modelo": "Classic", "cilindraje": 890, "color": ["gris", "naranja", "plateado"], "Combustible": "super", "placa": "YZA567", "precio": 5410055 },
    { "marca": "Motos Yamaha", "modelo": "GSX-R", "cilindraje": 557, "color": ["plateado", "Turquesa", "Marrón"], "Combustible": "super", "placa": "678PQR", "precio": 11269238 },
    { "marca": "Motos Honda", "modelo": "CB 125", "cilindraje": 945, "color": ["verde", "Turquesa", "gris"], "Combustible": "super", "placa": "WXY901", "precio": 7984204 },
    { "marca": "Royal Enfield", "modelo": "Splendor", "cilindraje": 941, "color": ["verde", "rojo y azul"], "Combustible": "super", "placa": "TUV678", "precio": 16245429 },
    { "marca": "Auteco", "modelo": "-Strom", "cilindraje": 938, "color": ["Turquesa", "verde"], "Combustible": "extra", "placa": "678TUV", "precio": 15946997 },
    { "marca": "AKT", "modelo": "Dominar", "cilindraje": 859, "color": ["plateado", "Turquesa"], "Combustible": "extra", "placa": "YZA567", "precio": 12075677 },
    { "marca": "Motos Suzuki", "modelo": "25 NKD", "cilindraje": 362, "color": ["amarillo", "Marrón"], "Combustible": "extra", "placa": "GHI789", "precio": 15066840 },
    { "marca": "Motos Suzuki", "modelo": "250 Adventure", "cilindraje": 540, "color": ["gris"], "Combustible": "extra", "placa": "HIJ456", "precio": 13070185 },
    { "marca": "AKT", "modelo": "25 NKD", "cilindraje": 778, "color": ["Turquesa", "Marrón"], "Combustible": "corriente", "placa": "567YZA", "precio": 8098032 },
    { "marca": "Auteco", "modelo": "Xpulse", "cilindraje": 510, "color": ["rojo y azul", "verde"], "Combustible": "super", "placa": "789KLM", "precio": 17704512 },
    { "marca": "Motos Suzuki", "modelo": "Pulsar", "cilindraje": 959, "color": ["naranja"], "Combustible": "super", "placa": "234ZAB", "precio": 15687053 },
    { "marca": "Motos Suzuki", "modelo": "CB 125", "cilindraje": 644, "color": ["verde", "negro"], "Combustible": "extra", "placa": "012JKL", "precio": 17266907 },
    { "marca": "Auteco", "modelo": "Pulsar", "cilindraje": 580, "color": ["Marrón", "blanco"], "Combustible": "corriente", "placa": "678TUV", "precio": 11567643 },
    { "marca": "Motos Yamaha", "modelo": "Ntorq", "cilindraje": 294, "color": ["naranja", "amarillo", "rojo y azul"], "Combustible": "corriente", "placa": "UVW345", "precio": 15110040 },
    { "marca": "AKT", "modelo": "25 NKD", "cilindraje": 962, "color": ["plateado", "verde", "Turquesa"], "Combustible": "super", "placa": "789OPQ", "precio": 15828141 },
    { "marca": "Motos Suzuki", "modelo": "Xpulse", "cilindraje": 470, "color": ["amarillo", "rojo y azul"], "Combustible": "super", "placa": "LMN456", "precio": 18211390 },
    { "marca": "Motos Honda", "modelo": "-Strom", "cilindraje": 332, "color": ["negro", "Marrón", "gris"], "Combustible": "super", "placa": "XYZ678", "precio": 18214775 },
    { "marca": "TVS", "modelo": "25 NKD", "cilindraje": 327, "color": ["Marrón"], "Combustible": "corriente", "placa": "ABC123", "precio": 15281231 },
    { "marca": "Hero", "modelo": "Splendor", "cilindraje": 726, "color": ["amarillo"], "Combustible": "extra", "placa": "345MNO", "precio": 17736391 },
    { "marca": "Royal Enfield", "modelo": "NMAX", "cilindraje": 819, "color": ["naranja"], "Combustible": "corriente", "placa": "901STU", "precio": 8465660 },
    { "marca": "Royal Enfield", "modelo": "CBR", "cilindraje": 883, "color": ["blanco", "negro", "naranja"], "Combustible": "super", "placa": "012JKL", "precio": 13261621 },
    { "marca": "AKT", "modelo": "CBR", "cilindraje": 264, "color": ["blanco", "Marrón"], "Combustible": "super", "placa": "QRS345", "precio": 13985415 },
    { "marca": "Motos Honda", "modelo": "NMAX", "cilindraje": 422, "color": ["gris"], "Combustible": "extra", "placa": "RST012", "precio": 9242382 },
    { "marca": "Auteco", "modelo": "Apache", "cilindraje": 737, "color": ["blanco", "Turquesa"], "Combustible": "super", "placa": "KLM789", "precio": 12969832 },
    { "marca": "Auteco", "modelo": "-Strom", "cilindraje": 884, "color": ["amarillo", "plateado"], "Combustible": "extra", "placa": "NOP012", "precio": 5344067 },
    { "marca": "Royal Enfield", "modelo": "Ntorq", "cilindraje": 286, "color": ["naranja", "verde", "negro"], "Combustible": "extra", "placa": "890BCD", "precio": 11729474 },
    { "marca": "Auteco", "modelo": "CBR", "cilindraje": 778, "color": ["Turquesa", "rojo y azul", "blanco"], "Combustible": "extra", "placa": "CDE567", "precio": 19475435 },
    { "marca": "Royal Enfield", "modelo": "Intercept", "cilindraje": 407, "color": ["gris", "negro"], "Combustible": "super", "placa": "OPQ789", "precio": 8730404 },
    { "marca": "TVS", "modelo": "Pulsar", "cilindraje": 643, "color": ["blanco", "negro", "amarillo"], "Combustible": "extra", "placa": "JKL012", "precio": 7583320 },
    { "marca": "TVS", "modelo": "Intercept", "cilindraje": 703, "color": ["verde"], "Combustible": "extra", "placa": "901WXY", "precio": 11564306 },
    { "marca": "Royal Enfield", "modelo": "CB 125", "cilindraje": 818, "color": ["Turquesa", "rojo y azul", "plateado"], "Combustible": "corriente", "placa": "678PQR", "precio": 9024402 },
    { "marca": "Royal Enfield", "modelo": "CBR", "cilindraje": 891, "color": ["verde", "amarillo", "naranja"], "Combustible": "extra", "placa": "DEF456", "precio": 12067544 },
    { "marca": "AKT", "modelo": "CB 125", "cilindraje": 658, "color": ["verde"], "Combustible": "super", "placa": "KLM789", "precio": 18094045 },
    { "marca": "Motos Suzuki", "modelo": "YZF-R", "cilindraje": 827, "color": ["blanco"], "Combustible": "super", "placa": "012RST", "precio": 9182454 },
    { "marca": "Motos Yamaha", "modelo": "250 Adventure", "cilindraje": 143, "color": ["gris", "Marrón", "Turquesa"], "Combustible": "corriente", "placa": "678TUV", "precio": 18157326 },
    { "marca": "AKT", "modelo": "Intercept", "cilindraje": 171, "color": ["Turquesa", "rojo y azul", "amarillo"], "Combustible": "extra", "placa": "YZA567", "precio": 7370047 },
    { "marca": "Motos Honda", "modelo": "Apache", "cilindraje": 603, "color": ["Marrón", "naranja"], "Combustible": "extra", "placa": "GHI789", "precio": 12927989 },
    { "marca": "Motos Honda", "modelo": "Dominar", "cilindraje": 583, "color": ["negro", "amarillo", "plateado"], "Combustible": "extra", "placa": "IJK123", "precio": 16850700 },
    { "marca": "TVS", "modelo": "Classic", "cilindraje": 794, "color": ["Turquesa"], "Combustible": "extra", "placa": "123EFG", "precio": 13720294 },
    { "marca": "Motos Yamaha", "modelo": "Intercept", "cilindraje": 137, "color": ["amarillo"], "Combustible": "corriente", "placa": "123IJK", "precio": 17632725 },
    { "marca": "Motos Suzuki", "modelo": "Classic", "cilindraje": 798, "color": ["verde", "blanco"], "Combustible": "super", "placa": "MNO345", "precio": 6250468 },
    { "marca": "AKT", "modelo": "Agility", "cilindraje": 119, "color": ["plateado", "gris"], "Combustible": "corriente", "placa": "789KLM", "precio": 5689589 },
    { "marca": "Motos Suzuki", "modelo": "Pulsar", "cilindraje": 167, "color": ["Marrón", "blanco", "Turquesa"], "Combustible": "super", "placa": "NOP012", "precio": 5045825 },
    { "marca": "AKT", "modelo": "Apache", "cilindraje": 909, "color": ["amarillo"], "Combustible": "super", "placa": "LMN456", "precio": 11058954 },
    { "marca": "Motos Suzuki", "modelo": "-Strom", "cilindraje": 166, "color": ["rojo y azul", "gris", "Marrón"], "Combustible": "extra", "placa": "DEF456", "precio": 9617036 },
    { "marca": "Motos Suzuki", "modelo": "CB 125", "cilindraje": 376, "color": ["gris", "amarillo", "plateado"], "Combustible": "corriente", "placa": "012RST", "precio": 5563881 },
    { "marca": "AKT", "modelo": "Apache", "cilindraje": 584, "color": ["amarillo", "negro", "Turquesa"], "Combustible": "corriente", "placa": "901WXY", "precio": 8311225 },
    { "marca": "Auteco", "modelo": "Classic", "cilindraje": 771, "color": ["amarillo"], "Combustible": "extra", "placa": "CDE567", "precio": 19296288 },
    { "marca": "Motos Suzuki", "modelo": "Classic", "cilindraje": 127, "color": ["negro"], "Combustible": "corriente", "placa": "IJK123", "precio": 8916034 },
    { "marca": "Motos Honda", "modelo": "Apache", "cilindraje": 232, "color": ["blanco", "amarillo"], "Combustible": "corriente", "placa": "890BCD", "precio": 4860143 },
    { "marca": "Auteco", "modelo": "CBR", "cilindraje": 742, "color": ["naranja", "amarillo"], "Combustible": "extra", "placa": "HIJ456", "precio": 15600807 },
    { "marca": "Motos Honda", "modelo": "Agility", "cilindraje": 750, "color": ["naranja", "plateado", "negro"], "Combustible": "extra", "placa": "456HIJ", "precio": 9755788 },
    { "marca": "Motos Yamaha", "modelo": "NMAX", "cilindraje": 549, "color": ["negro", "amarillo", "Turquesa"], "Combustible": "corriente", "placa": "ZAB234", "precio": 17220956 },
    { "marca": "Royal Enfield", "modelo": "Intercept", "cilindraje": 920, "color": ["blanco"], "Combustible": "corriente", "placa": "NOP012", "precio": 9333893 },
    { "marca": "Motos Honda", "modelo": "Xpulse", "cilindraje": 723, "color": ["negro"], "Combustible": "corriente", "placa": "MNO345", "precio": 12486849 },
    { "marca": "Hero", "modelo": "Classic", "cilindraje": 326, "color": ["blanco", "plateado", "Turquesa"], "Combustible": "extra", "placa": "RST012", "precio": 16860432 },
    { "marca": "Motos Yamaha", "modelo": "Agility", "cilindraje": 465, "color": ["Marrón", "naranja"], "Combustible": "corriente", "placa": "890FGH", "precio": 7299113 },
    { "marca": "TVS", "modelo": "25 NKD", "cilindraje": 281, "color": ["Turquesa", "blanco", "amarillo"], "Combustible": "corriente", "placa": "234VWX", "precio": 19905823 },
    { "marca": "Auteco", "modelo": "Splendor", "cilindraje": 844, "color": ["Marrón"], "Combustible": "corriente", "placa": "MNO345", "precio": 13419045 },
    { "marca": "Motos Suzuki", "modelo": "Xpulse", "cilindraje": 899, "color": ["Marrón"], "Combustible": "super", "placa": "IJK123", "precio": 19976680 },
    { "marca": "TVS", "modelo": "Pulsar", "cilindraje": 823, "color": ["negro", "Marrón"], "Combustible": "super", "placa": "345QRS", "precio": 13126248 },
    { "marca": "Motos Yamaha", "modelo": "25 NKD", "cilindraje": 865, "color": ["negro"], "Combustible": "corriente", "placa": "234VWX", "precio": 12326513 },
    { "marca": "Hero", "modelo": "25 NKD", "cilindraje": 643, "color": ["Turquesa"], "Combustible": "extra", "placa": "789KLM", "precio": 9269508 },
    { "marca": "Royal Enfield", "modelo": "-Strom", "cilindraje": 793, "color": ["gris", "verde"], "Combustible": "super", "placa": "345QRS", "precio": 12300331 },
    { "marca": "TVS", "modelo": "Apache", "cilindraje": 679, "color": ["amarillo", "rojo y azul", "naranja"], "Combustible": "corriente", "placa": "345MNO", "precio": 14639602 },
    { "marca": "Royal Enfield", "modelo": "-Strom", "cilindraje": 570, "color": ["Marrón", "Turquesa"], "Combustible": "super", "placa": "123IJK", "precio": 19379520 },
    { "marca": "Motos Suzuki", "modelo": "Intercept", "cilindraje": 184, "color": ["Marrón", "negro"], "Combustible": "corriente", "placa": "OPQ789", "precio": 13189905 },
    { "marca": "Royal Enfield", "modelo": "Xpulse", "cilindraje": 304, "color": ["Marrón"], "Combustible": "corriente", "placa": "123EFG", "precio": 11860102 },
    { "marca": "Auteco", "modelo": "Agility", "cilindraje": 184, "color": ["blanco"], "Combustible": "corriente", "placa": "IJK123", "precio": 16549318 },
    { "marca": "Motos Suzuki", "modelo": "Pulsar", "cilindraje": 423, "color": ["negro", "verde"], "Combustible": "super", "placa": "678PQR", "precio": 5876914 },
    { "marca": "TVS", "modelo": "250 Adventure", "cilindraje": 148, "color": ["naranja", "blanco", "gris"], "Combustible": "corriente", "placa": "CDE567", "precio": 13132786 },
    { "marca": "Motos Honda", "modelo": "NMAX", "cilindraje": 945, "color": ["naranja", "negro", "verde"], "Combustible": "corriente", "placa": "MNO345", "precio": 12137863 },
    { "marca": "Motos Yamaha", "modelo": "CB 125", "cilindraje": 120, "color": ["negro", "naranja"], "Combustible": "extra", "placa": "012RST", "precio": 16045145 },
    { "marca": "Royal Enfield", "modelo": "Agility", "cilindraje": 170, "color": ["gris", "Marrón", "naranja"], "Combustible": "corriente", "placa": "JKL012", "precio": 17350444 },
    { "marca": "AKT", "modelo": "Intercept", "cilindraje": 249, "color": ["blanco", "amarillo"], "Combustible": "corriente", "placa": "567CDE", "precio": 8689289 },
    { "marca": "TVS", "modelo": "Apache", "cilindraje": 527, "color": ["negro", "gris", "Marrón"], "Combustible": "super", "placa": "QRS345", "precio": 15325693 },
    { "marca": "Auteco", "modelo": "YZF-R", "cilindraje": 737, "color": ["naranja"], "Combustible": "super", "placa": "EFG123", "precio": 15266549 },
    { "marca": "Auteco", "modelo": "Intercept", "cilindraje": 750, "color": ["negro", "naranja", "Marrón"], "Combustible": "super", "placa": "XYZ678", "precio": 7945289 },
    { "marca": "TVS", "modelo": "Xpulse", "cilindraje": 925, "color": ["blanco"], "Combustible": "super", "placa": "EFG123", "precio": 17486352 },
    { "marca": "TVS", "modelo": "CBR", "cilindraje": 551, "color": ["plateado", "verde"], "Combustible": "extra", "placa": "GHI789", "precio": 16450601 },
    { "marca": "Auteco", "modelo": "Pulsar", "cilindraje": 833, "color": ["negro", "amarillo", "naranja"], "Combustible": "corriente", "placa": "QRS345", "precio": 9676602 },
    { "marca": "Motos Honda", "modelo": "fz25", "cilindraje": 876, "color": ["Marrón", "gris"], "Combustible": "super", "placa": "CDE567", "precio": 13508858 },
    { "marca": "Motos Suzuki", "modelo": "Ntorq", "cilindraje": 651, "color": ["amarillo", "rojo y azul", "Marrón"], "Combustible": "extra", "placa": "789KLM", "precio": 14407788 },
    { "marca": "Hero", "modelo": "fz25", "cilindraje": 134, "color": ["gris"], "Combustible": "extra", "placa": "901STU", "precio": 19979758 },
    { "marca": "Motos Yamaha", "modelo": "GSX-R", "cilindraje": 929, "color": ["Marrón", "gris"], "Combustible": "corriente", "placa": "OPQ789", "precio": 14714377 },
    { "marca": "Motos Suzuki", "modelo": "250 Adventure", "cilindraje": 406, "color": ["negro", "amarillo", "Turquesa"], "Combustible": "extra", "placa": "678TUV", "precio": 6447093 },
    { "marca": "Hero", "modelo": "CBR", "cilindraje": 124, "color": ["naranja", "Turquesa", "verde"], "Combustible": "corriente", "placa": "OPQ789", "precio": 16491306 },
    { "marca": "Auteco", "modelo": "fz25", "cilindraje": 655, "color": ["plateado"], "Combustible": "extra", "placa": "EFG123", "precio": 7851763 },
    { "marca": "Royal Enfield", "modelo": "Pulsar", "cilindraje": 164, "color": ["rojo y azul"], "Combustible": "extra", "placa": "456DEF", "precio": 4710272 },
    { "marca": "Motos Yamaha", "modelo": "Dominar", "cilindraje": 172, "color": ["blanco", "verde"], "Combustible": "super", "placa": "012JKL", "precio": 10374177 },
    { "marca": "AKT", "modelo": "250 Adventure", "cilindraje": 675, "color": ["verde", "amarillo"], "Combustible": "corriente", "placa": "567YZA", "precio": 17127719 },
    { "marca": "Motos Honda", "modelo": "NMAX", "cilindraje": 518, "color": ["Marrón"], "Combustible": "extra", "placa": "KLM789", "precio": 7412650 },
    { "marca": "Royal Enfield", "modelo": "250 Adventure", "cilindraje": 165, "color": ["naranja", "Marrón"], "Combustible": "super", "placa": "KLM789", "precio": 17466305 },
    { "marca": "Motos Yamaha", "modelo": "CBR", "cilindraje": 919, "color": ["plateado"], "Combustible": "corriente", "placa": "PQR678", "precio": 19916790 },
    { "marca": "Auteco", "modelo": "Xpulse", "cilindraje": 597, "color": ["gris", "Turquesa", "verde"], "Combustible": "corriente", "placa": "QRS345", "precio": 15639927 },
    { "marca": "TVS", "modelo": "Intercept", "cilindraje": 965, "color": ["Turquesa", "verde", "naranja"], "Combustible": "extra", "placa": "123IJK", "precio": 12930835 },
    { "marca": "Motos Yamaha", "modelo": "Xpulse", "cilindraje": 576, "color": ["rojo y azul", "amarillo"], "Combustible": "extra", "placa": "ZAB234", "precio": 7985428 },
    { "marca": "Motos Suzuki", "modelo": "NMAX", "cilindraje": 672, "color": ["blanco", "Turquesa", "gris"], "Combustible": "super", "placa": "789KLM", "precio": 5896549 },
    { "marca": "Hero", "modelo": "Pulsar", "cilindraje": 216, "color": ["verde", "amarillo"], "Combustible": "extra", "placa": "567CDE", "precio": 14872361 },
    { "marca": "Auteco", "modelo": "Pulsar", "cilindraje": 541, "color": ["blanco", "Marrón"], "Combustible": "extra", "placa": "UVW345", "precio": 19349020 },
    { "marca": "Motos Suzuki", "modelo": "Apache", "cilindraje": 388, "color": ["Turquesa", "naranja"], "Combustible": "extra", "placa": "012RST", "precio": 6259007 },
    { "marca": "Motos Suzuki", "modelo": "CB 125", "cilindraje": 741, "color": ["Marrón"], "Combustible": "extra", "placa": "YZA567", "precio": 11231881 },
    { "marca": "Motos Yamaha", "modelo": "CB 125", "cilindraje": 522, "color": ["negro"], "Combustible": "extra", "placa": "MNO345", "precio": 8124882 },
    { "marca": "Royal Enfield", "modelo": "GSX-R", "cilindraje": 775, "color": ["plateado", "negro"], "Combustible": "extra", "placa": "678PQR", "precio": 11534051 },
    { "marca": "Motos Suzuki", "modelo": "Intercept", "cilindraje": 591, "color": ["naranja", "rojo y azul", "blanco"], "Combustible": "extra", "placa": "456HIJ", "precio": 10564947 },
    { "marca": "Motos Honda", "modelo": "25 NKD", "cilindraje": 573, "color": ["blanco", "Turquesa"], "Combustible": "super", "placa": "XYZ678", "precio": 16198472 },
    { "marca": "Motos Suzuki", "modelo": "Classic", "cilindraje": 954, "color": ["Marrón"], "Combustible": "super", "placa": "567YZA", "precio": 8596868 },
    { "marca": "Motos Yamaha", "modelo": "fz25", "cilindraje": 493, "color": ["rojo y azul", "amarillo", "negro"], "Combustible": "corriente", "placa": "STU901", "precio": 17955997 },
    { "marca": "Motos Suzuki", "modelo": "Xpulse", "cilindraje": 284, "color": ["gris", "plateado", "verde"], "Combustible": "extra", "placa": "STU901", "precio": 4505465 },
    { "marca": "AKT", "modelo": "Africa Twin", "cilindraje": 707, "color": ["blanco", "rojo y azul"], "Combustible": "corriente", "placa": "890BCD", "precio": 9213813 },
    { "marca": "Motos Yamaha", "modelo": "-Strom", "cilindraje": 271, "color": ["gris"], "Combustible": "super", "placa": "EFG123", "precio": 7757108 },
    { "marca": "Royal Enfield", "modelo": "Splendor", "cilindraje": 765, "color": ["gris", "naranja"], "Combustible": "corriente", "placa": "EFG123", "precio": 13720853 },
    { "marca": "Hero", "modelo": "YZF-R", "cilindraje": 726, "color": ["blanco", "amarillo", "gris"], "Combustible": "extra", "placa": "ZAB234", "precio": 10122069 },
    { "marca": "Motos Yamaha", "modelo": "Xpulse", "cilindraje": 942, "color": ["naranja"], "Combustible": "extra", "placa": "CDE567", "precio": 5196034 },
    { "marca": "Hero", "modelo": "fz25", "cilindraje": 744, "color": ["Marrón", "naranja"], "Combustible": "corriente", "placa": "BCD890", "precio": 11876637 },
    { "marca": "Motos Honda", "modelo": "fz25", "cilindraje": 663, "color": ["gris"], "Combustible": "corriente", "placa": "789KLM", "precio": 18039571 },
    { "marca": "Auteco", "modelo": "fz25", "cilindraje": 957, "color": ["Marrón", "gris"], "Combustible": "super", "placa": "KLM789", "precio": 9133518 },
    { "marca": "AKT", "modelo": "NMAX", "cilindraje": 360, "color": ["negro"], "Combustible": "extra", "placa": "123ABC", "precio": 17653329 },
    { "marca": "Auteco", "modelo": "Dominar", "cilindraje": 436, "color": ["negro"], "Combustible": "extra", "placa": "012NOP", "precio": 17942362 },
    { "marca": "Hero", "modelo": "Agility", "cilindraje": 330, "color": ["Marrón", "plateado"], "Combustible": "extra", "placa": "VWX234", "precio": 15316241 },
    { "marca": "Royal Enfield", "modelo": "YZF-R", "cilindraje": 606, "color": ["amarillo"], "Combustible": "extra", "placa": "XYZ678", "precio": 7220026 },
    { "marca": "TVS", "modelo": "fz25", "cilindraje": 721, "color": ["negro"], "Combustible": "extra", "placa": "KLM789", "precio": 14350255 },
    { "marca": "Motos Suzuki", "modelo": "fz25", "cilindraje": 650, "color": ["Turquesa", "blanco", "rojo y azul"], "Combustible": "extra", "placa": "567CDE", "precio": 6695854 },
    { "marca": "Motos Yamaha", "modelo": "Agility", "cilindraje": 846, "color": ["naranja", "Turquesa"], "Combustible": "extra", "placa": "EFG123", "precio": 11617781 },
    { "marca": "AKT", "modelo": "Pulsar", "cilindraje": 765, "color": ["rojo y azul"], "Combustible": "extra", "placa": "678PQR", "precio": 4905101 },
    { "marca": "TVS", "modelo": "GSX-R", "cilindraje": 689, "color": ["gris", "naranja", "Marrón"], "Combustible": "extra", "placa": "ABC123", "precio": 10633276 },
    { "marca": "Auteco", "modelo": "CBR", "cilindraje": 665, "color": ["plateado"], "Combustible": "corriente", "placa": "XYZ678", "precio": 6952106 },
    { "marca": "AKT", "modelo": "CBR", "cilindraje": 127, "color": ["gris"], "Combustible": "corriente", "placa": "234VWX", "precio": 19121623 },
    { "marca": "Motos Yamaha", "modelo": "Ntorq", "cilindraje": 114, "color": ["plateado"], "Combustible": "super", "placa": "789OPQ", "precio": 15474646 },
    { "marca": "Royal Enfield", "modelo": "Intercept", "cilindraje": 807, "color": ["rojo y azul", "gris"], "Combustible": "super", "placa": "TUV678", "precio": 18908552 },
    { "marca": "Hero", "modelo": "GSX-R", "cilindraje": 381, "color": ["Turquesa", "Marrón"], "Combustible": "extra", "placa": "QRS345", "precio": 6555608 },
    { "marca": "Royal Enfield", "modelo": "Dominar", "cilindraje": 144, "color": ["verde"], "Combustible": "corriente", "placa": "CDE567", "precio": 5358271 },
    { "marca": "Hero", "modelo": "GSX-R", "cilindraje": 662, "color": ["negro", "gris", "naranja"], "Combustible": "extra", "placa": "901STU", "precio": 15645078 },
    { "marca": "Motos Yamaha", "modelo": "NMAX", "cilindraje": 673, "color": ["verde", "blanco"], "Combustible": "corriente", "placa": "123ABC", "precio": 17742160 },
    { "marca": "Motos Suzuki", "modelo": "NMAX", "cilindraje": 719, "color": ["blanco", "verde", "gris"], "Combustible": "extra", "placa": "WXY901", "precio": 5677907 },
    { "marca": "Hero", "modelo": "Pulsar", "cilindraje": 653, "color": ["naranja", "Marrón"], "Combustible": "super", "placa": "012RST", "precio": 13529521 },
    { "marca": "AKT", "modelo": "Apache", "cilindraje": 206, "color": ["negro"], "Combustible": "extra", "placa": "789GHI", "precio": 9038053 },
    { "marca": "Motos Yamaha", "modelo": "fz25", "cilindraje": 923, "color": ["naranja", "plateado"], "Combustible": "extra", "placa": "789KLM", "precio": 6941754 },
    { "marca": "Motos Suzuki", "modelo": "YZF-R", "cilindraje": 983, "color": ["gris", "Turquesa"], "Combustible": "super", "placa": "NOP012", "precio": 14380737 },
    { "marca": "Motos Honda", "modelo": "fz25", "cilindraje": 130, "color": ["Turquesa", "negro", "amarillo"], "Combustible": "corriente", "placa": "901STU", "precio": 18349470 },
    { "marca": "Motos Suzuki", "modelo": "Splendor", "cilindraje": 225, "color": ["rojo y azul", "naranja"], "Combustible": "corriente", "placa": "MNO345", "precio": 7402738 },
    { "marca": "Motos Suzuki", "modelo": "GSX-R", "cilindraje": 417, "color": ["plateado", "naranja", "amarillo"], "Combustible": "corriente", "placa": "NOP012", "precio": 10872430 },
    { "marca": "Motos Yamaha", "modelo": "Classic", "cilindraje": 458, "color": ["Marrón", "rojo y azul", "gris"], "Combustible": "corriente", "placa": "890BCD", "precio": 11687882 },
    { "marca": "TVS", "modelo": "NMAX", "cilindraje": 274, "color": ["naranja", "verde", "rojo y azul"], "Combustible": "corriente", "placa": "901STU", "precio": 14716031 },
    { "marca": "Royal Enfield", "modelo": "NMAX", "cilindraje": 162, "color": ["gris", "naranja"], "Combustible": "super", "placa": "YZA567", "precio": 15594574 },
    { "marca": "Motos Suzuki", "modelo": "Dominar", "cilindraje": 475, "color": ["naranja", "Turquesa", "amarillo"], "Combustible": "corriente", "placa": "345MNO", "precio": 12415915 },
    { "marca": "Hero", "modelo": "Classic", "cilindraje": 936, "color": ["Turquesa", "verde", "Marrón"], "Combustible": "corriente", "placa": "123ABC", "precio": 17161817 },
    { "marca": "TVS", "modelo": "YZF-R", "cilindraje": 260, "color": ["blanco", "naranja", "gris"], "Combustible": "super", "placa": "456HIJ", "precio": 18323278 },
    { "marca": "Motos Honda", "modelo": "Splendor", "cilindraje": 721, "color": ["blanco", "Marrón"], "Combustible": "extra", "placa": "BCD890", "precio": 6092304 },
    { "marca": "TVS", "modelo": "fz25", "cilindraje": 522, "color": ["Turquesa"], "Combustible": "super", "placa": "QRS345", "precio": 9051600 },
    { "marca": "TVS", "modelo": "NMAX", "cilindraje": 613, "color": ["amarillo"], "Combustible": "extra", "placa": "DEF456", "precio": 13688189 },
    { "marca": "TVS", "modelo": "Dominar", "cilindraje": 997, "color": ["gris", "amarillo"], "Combustible": "extra", "placa": "012RST", "precio": 11795484 },
    { "marca": "AKT", "modelo": "Dominar", "cilindraje": 804, "color": ["Turquesa", "verde"], "Combustible": "super", "placa": "TUV678", "precio": 16959967 },
    { "marca": "AKT", "modelo": "CB 125", "cilindraje": 804, "color": ["plateado"], "Combustible": "extra", "placa": "WXY901", "precio": 17245042 },
    { "marca": "AKT", "modelo": "fz25", "cilindraje": 585, "color": ["negro", "naranja", "blanco"], "Combustible": "corriente", "placa": "UVW345", "precio": 19137035 },
    { "marca": "Motos Yamaha", "modelo": "Intercept", "cilindraje": 774, "color": ["naranja", "amarillo", "rojo y azul"], "Combustible": "super", "placa": "345QRS", "precio": 15629732 },
    { "marca": "TVS", "modelo": "-Strom", "cilindraje": 847, "color": ["verde", "Marrón"], "Combustible": "corriente", "placa": "IJK123", "precio": 18321475 },
    { "marca": "Royal Enfield", "modelo": "Africa Twin", "cilindraje": 249, "color": ["amarillo"], "Combustible": "corriente", "placa": "NOP012", "precio": 15943616 },
    { "marca": "TVS", "modelo": "GSX-R", "cilindraje": 620, "color": ["Turquesa"], "Combustible": "super", "placa": "789GHI", "precio": 5555569 },
    { "marca": "Hero", "modelo": "Africa Twin", "cilindraje": 756, "color": ["Marrón", "Turquesa", "verde"], "Combustible": "super", "placa": "EFG123", "precio": 19678719 },
    { "marca": "TVS", "modelo": "Classic", "cilindraje": 573, "color": ["negro", "rojo y azul"], "Combustible": "corriente", "placa": "PQR678", "precio": 17588069 },
    { "marca": "TVS", "modelo": "NMAX", "cilindraje": 602, "color": ["Turquesa"], "Combustible": "extra", "placa": "BCD890", "precio": 17217079 },
    { "marca": "Auteco", "modelo": "Ntorq", "cilindraje": 323, "color": ["gris", "blanco"], "Combustible": "super", "placa": "WXY901", "precio": 16307068 },
    { "marca": "AKT", "modelo": "YZF-R", "cilindraje": 383, "color": ["naranja"], "Combustible": "extra", "placa": "789GHI", "precio": 12613345 },
    { "marca": "Motos Honda", "modelo": "Splendor", "cilindraje": 217, "color": ["naranja", "Turquesa", "Marrón"], "Combustible": "super", "placa": "LMN456", "precio": 6962437 },
    { "marca": "Hero", "modelo": "Pulsar", "cilindraje": 822, "color": ["Marrón", "amarillo"], "Combustible": "super", "placa": "123ABC", "precio": 17416397 },
    { "marca": "Royal Enfield", "modelo": "CB 125", "cilindraje": 737, "color": ["amarillo", "negro"], "Combustible": "extra", "placa": "WXY901", "precio": 9798185 },
    { "marca": "Motos Suzuki", "modelo": "Intercept", "cilindraje": 746, "color": ["plateado", "gris", "verde"], "Combustible": "super", "placa": "789GHI", "precio": 10706848 },
    { "marca": "Royal Enfield", "modelo": "-Strom", "cilindraje": 955, "color": ["blanco"], "Combustible": "extra", "placa": "789KLM", "precio": 13047925 },
    { "marca": "Hero", "modelo": "Classic", "cilindraje": 751, "color": ["Marrón", "Turquesa", "rojo y azul"], "Combustible": "corriente", "placa": "GHI789", "precio": 18572717 },
    { "marca": "TVS", "modelo": "Apache", "cilindraje": 312, "color": ["Marrón", "Turquesa"], "Combustible": "extra", "placa": "KLM789", "precio": 8588108 },
    { "marca": "Motos Suzuki", "modelo": "Ntorq", "cilindraje": 282, "color": ["verde", "gris"], "Combustible": "super", "placa": "890FGH", "precio": 11585970 },
    { "marca": "Motos Suzuki", "modelo": "Ntorq", "cilindraje": 484, "color": ["verde", "blanco", "amarillo"], "Combustible": "super", "placa": "678PQR", "precio": 12088884 },
    { "marca": "Motos Honda", "modelo": "Splendor", "cilindraje": 966, "color": ["verde"], "Combustible": "extra", "placa": "345MNO", "precio": 12004216 },
    { "marca": "TVS", "modelo": "NMAX", "cilindraje": 490, "color": ["rojo y azul", "naranja", "negro"], "Combustible": "corriente", "placa": "012RST", "precio": 4803125 },
    { "marca": "Royal Enfield", "modelo": "Agility", "cilindraje": 304, "color": ["plateado", "blanco"], "Combustible": "corriente", "placa": "456DEF", "precio": 18543853 },
    { "marca": "Auteco", "modelo": "250 Adventure", "cilindraje": 970, "color": ["plateado"], "Combustible": "super", "placa": "456LMN", "precio": 9898794 },
    { "marca": "Motos Honda", "modelo": "CBR", "cilindraje": 245, "color": ["Marrón", "verde", "amarillo"], "Combustible": "corriente", "placa": "901WXY", "precio": 6221910 },
    { "marca": "Motos Suzuki", "modelo": "Pulsar", "cilindraje": 653, "color": ["amarillo"], "Combustible": "extra", "placa": "234ZAB", "precio": 7720228 },
    { "marca": "Motos Honda", "modelo": "Ntorq", "cilindraje": 272, "color": ["gris"], "Combustible": "extra", "placa": "901STU", "precio": 11406849 },
    { "marca": "Royal Enfield", "modelo": "250 Adventure", "cilindraje": 664, "color": ["Turquesa", "plateado", "gris"], "Combustible": "super", "placa": "NOP012", "precio": 9033424 },
    { "marca": "Motos Suzuki", "modelo": "-Strom", "cilindraje": 190, "color": ["Marrón", "negro"], "Combustible": "corriente", "placa": "567CDE", "precio": 10259199 },
    { "marca": "TVS", "modelo": "25 NKD", "cilindraje": 490, "color": ["plateado"], "Combustible": "corriente", "placa": "890BCD", "precio": 16554102 },
    { "marca": "AKT", "modelo": "25 NKD", "cilindraje": 428, "color": ["amarillo"], "Combustible": "corriente", "placa": "TUV678", "precio": 12513722 },
    { "marca": "Royal Enfield", "modelo": "-Strom", "cilindraje": 513, "color": ["Marrón", "rojo y azul"], "Combustible": "corriente", "placa": "012JKL", "precio": 5627175 },
    { "marca": "Motos Yamaha", "modelo": "YZF-R", "cilindraje": 244, "color": ["Turquesa", "negro"], "Combustible": "corriente", "placa": "JKL012", "precio": 14277424 },
    { "marca": "Auteco", "modelo": "Classic", "cilindraje": 894, "color": ["plateado", "rojo y azul"], "Combustible": "extra", "placa": "IJK123", "precio": 15872361 },
    { "marca": "Hero", "modelo": "Intercept", "cilindraje": 372, "color": ["rojo y azul", "plateado"], "Combustible": "super", "placa": "678PQR", "precio": 7539307 },
    { "marca": "Hero", "modelo": "YZF-R", "cilindraje": 725, "color": ["blanco", "amarillo", "negro"], "Combustible": "extra", "placa": "456HIJ", "precio": 15821554 },
    { "marca": "Motos Honda", "modelo": "Splendor", "cilindraje": 831, "color": ["blanco", "Turquesa", "verde"], "Combustible": "extra", "placa": "ABC123", "precio": 9512660 },
    { "marca": "TVS", "modelo": "25 NKD", "cilindraje": 633, "color": ["Marrón"], "Combustible": "corriente", "placa": "BCD890", "precio": 13580627 },
    { "marca": "Motos Suzuki", "modelo": "YZF-R", "cilindraje": 104, "color": ["amarillo", "negro", "naranja"], "Combustible": "extra", "placa": "YZA567", "precio": 14720893 },
    { "marca": "AKT", "modelo": "fz25", "cilindraje": 324, "color": ["negro"], "Combustible": "extra", "placa": "NOP012", "precio": 13417910 },
    { "marca": "Royal Enfield", "modelo": "GSX-R", "cilindraje": 169, "color": ["blanco"], "Combustible": "extra", "placa": "WXY901", "precio": 11500987 },
    { "marca": "Motos Suzuki", "modelo": "Dominar", "cilindraje": 560, "color": ["negro", "Marrón", "naranja"], "Combustible": "corriente", "placa": "890BCD", "precio": 4717532 },
    { "marca": "Motos Yamaha", "modelo": "Pulsar", "cilindraje": 536, "color": ["amarillo"], "Combustible": "corriente", "placa": "FGH890", "precio": 7215951 },
    { "marca": "Auteco", "modelo": "NMAX", "cilindraje": 458, "color": ["Turquesa", "gris"], "Combustible": "corriente", "placa": "678PQR", "precio": 11826111 },
    { "marca": "Hero", "modelo": "Splendor", "cilindraje": 348, "color": ["naranja", "rojo y azul", "plateado"], "Combustible": "extra", "placa": "789OPQ", "precio": 9535998 },
    { "marca": "TVS", "modelo": "Classic", "cilindraje": 506, "color": ["amarillo"], "Combustible": "extra", "placa": "789GHI", "precio": 17530622 },
    { "marca": "Auteco", "modelo": "Apache", "cilindraje": 814, "color": ["amarillo"], "Combustible": "extra", "placa": "LMN456", "precio": 11648689 },
    { "marca": "Auteco", "modelo": "CBR", "cilindraje": 605, "color": ["Marrón", "Turquesa"], "Combustible": "extra", "placa": "TUV678", "precio": 19689705 },
    { "marca": "Royal Enfield", "modelo": "Apache", "cilindraje": 404, "color": ["blanco"], "Combustible": "extra", "placa": "CDE567", "precio": 18472994 },
    { "marca": "Auteco", "modelo": "-Strom", "cilindraje": 889, "color": ["plateado", "Marrón", "naranja"], "Combustible": "super", "placa": "012RST", "precio": 13121045 },
    { "marca": "Motos Honda", "modelo": "Apache", "cilindraje": 874, "color": ["naranja", "verde"], "Combustible": "super", "placa": "JKL012", "precio": 6409011 },
    { "marca": "AKT", "modelo": "250 Adventure", "cilindraje": 911, "color": ["naranja", "negro"], "Combustible": "corriente", "placa": "LMN456", "precio": 10862577 },
    { "marca": "Auteco", "modelo": "Xpulse", "cilindraje": 857, "color": ["Turquesa"], "Combustible": "corriente", "placa": "123EFG", "precio": 15095941 },
    { "marca": "Motos Honda", "modelo": "Dominar", "cilindraje": 847, "color": ["gris"], "Combustible": "corriente", "placa": "ZAB234", "precio": 12833443 },
    { "marca": "Motos Suzuki", "modelo": "YZF-R", "cilindraje": 366, "color": ["gris", "Turquesa"], "Combustible": "super", "placa": "ABC123", "precio": 9424794 },
    { "marca": "Hero", "modelo": "NMAX", "cilindraje": 808, "color": ["amarillo"], "Combustible": "extra", "placa": "012JKL", "precio": 11899207 },
    { "marca": "Motos Suzuki", "modelo": "Dominar", "cilindraje": 859, "color": ["gris", "negro", "verde"], "Combustible": "extra", "placa": "ZAB234", "precio": 12452595 },
    { "marca": "Motos Yamaha", "modelo": "Pulsar", "cilindraje": 878, "color": ["Marrón", "rojo y azul"], "Combustible": "extra", "placa": "PQR678", "precio": 5475133 },
    { "marca": "Royal Enfield", "modelo": "250 Adventure", "cilindraje": 301, "color": ["blanco"], "Combustible": "extra", "placa": "123ABC", "precio": 11798375 },
    { "marca": "TVS", "modelo": "GSX-R", "cilindraje": 584, "color": ["Turquesa"], "Combustible": "corriente", "placa": "890FGH", "precio": 15992470 },
    { "marca": "Motos Yamaha", "modelo": "YZF-R", "cilindraje": 951, "color": ["rojo y azul", "Marrón"], "Combustible": "corriente", "placa": "BCD890", "precio": 17562364 },
    { "marca": "Motos Honda", "modelo": "Intercept", "cilindraje": 991, "color": ["naranja", "blanco"], "Combustible": "extra", "placa": "IJK123", "precio": 19182263 },
    { "marca": "Auteco", "modelo": "Dominar", "cilindraje": 401, "color": ["amarillo", "Marrón", "negro"], "Combustible": "super", "placa": "123IJK", "precio": 8246176 },
    { "marca": "AKT", "modelo": "-Strom", "cilindraje": 291, "color": ["plateado", "gris", "blanco"], "Combustible": "extra", "placa": "901WXY", "precio": 13655528 },
    { "marca": "Hero", "modelo": "Xpulse", "cilindraje": 903, "color": ["negro"], "Combustible": "corriente", "placa": "KLM789", "precio": 12694257 },
    { "marca": "Royal Enfield", "modelo": "Intercept", "cilindraje": 270, "color": ["negro", "amarillo"], "Combustible": "corriente", "placa": "KLM789", "precio": 11806552 },
    { "marca": "Motos Honda", "modelo": "Classic", "cilindraje": 261, "color": ["plateado"], "Combustible": "extra", "placa": "ZAB234", "precio": 15049424 },
    { "marca": "Royal Enfield", "modelo": "fz25", "cilindraje": 447, "color": ["verde", "Marrón"], "Combustible": "extra", "placa": "HIJ456", "precio": 7398847 },
    { "marca": "Royal Enfield", "modelo": "YZF-R", "cilindraje": 665, "color": ["rojo y azul", "plateado", "naranja"], "Combustible": "corriente", "placa": "CDE567", "precio": 4938017 },
    { "marca": "Royal Enfield", "modelo": "25 NKD", "cilindraje": 99, "color": ["negro"], "Combustible": "extra", "placa": "567CDE", "precio": 14252202 },
    { "marca": "Motos Suzuki", "modelo": "Africa Twin", "cilindraje": 700, "color": ["rojo y azul"], "Combustible": "super", "placa": "789GHI", "precio": 18392302 },
    { "marca": "Hero", "modelo": "Intercept", "cilindraje": 419, "color": ["Turquesa"], "Combustible": "super", "placa": "345MNO", "precio": 9286037 },
    { "marca": "Motos Yamaha", "modelo": "NMAX", "cilindraje": 439, "color": ["plateado", "amarillo", "gris"], "Combustible": "corriente", "placa": "CDE567", "precio": 14429149 },
    { "marca": "Motos Suzuki", "modelo": "GSX-R", "cilindraje": 556, "color": ["rojo y azul", "naranja", "Turquesa"], "Combustible": "corriente", "placa": "DEF456", "precio": 4506374 },
    { "marca": "Motos Honda", "modelo": "Intercept", "cilindraje": 368, "color": ["Marrón", "verde", "naranja"], "Combustible": "super", "placa": "IJK123", "precio": 16551563 },
    { "marca": "TVS", "modelo": "YZF-R", "cilindraje": 429, "color": ["naranja"], "Combustible": "super", "placa": "789OPQ", "precio": 17035713 },
    { "marca": "Motos Honda", "modelo": "Ntorq", "cilindraje": 766, "color": ["Turquesa", "naranja"], "Combustible": "extra", "placa": "678PQR", "precio": 7020865 },
    { "marca": "Motos Yamaha", "modelo": "fz25", "cilindraje": 298, "color": ["naranja", "plateado", "negro"], "Combustible": "corriente", "placa": "VWX234", "precio": 12216800 },
    { "marca": "Auteco", "modelo": "25 NKD", "cilindraje": 460, "color": ["negro"], "Combustible": "super", "placa": "012JKL", "precio": 17356968 },
    { "marca": "AKT", "modelo": "25 NKD", "cilindraje": 831, "color": ["Marrón"], "Combustible": "extra", "placa": "890BCD", "precio": 11921652 },
    { "marca": "Auteco", "modelo": "Ntorq", "cilindraje": 521, "color": ["blanco", "Marrón", "verde"], "Combustible": "extra", "placa": "567YZA", "precio": 8609187 },
    { "marca": "AKT", "modelo": "fz25", "cilindraje": 910, "color": ["verde"], "Combustible": "corriente", "placa": "012JKL", "precio": 19044827 },
    { "marca": "TVS", "modelo": "YZF-R", "cilindraje": 201, "color": ["plateado", "amarillo", "negro"], "Combustible": "super", "placa": "456DEF", "precio": 13319624 },
    { "marca": "TVS", "modelo": "-Strom", "cilindraje": 596, "color": ["gris"], "Combustible": "super", "placa": "CDE567", "precio": 6398806 },
    { "marca": "Royal Enfield", "modelo": "Classic", "cilindraje": 209, "color": ["plateado"], "Combustible": "corriente", "placa": "CDE567", "precio": 9248014 },
    { "marca": "Royal Enfield", "modelo": "fz25", "cilindraje": 108, "color": ["gris", "amarillo"], "Combustible": "super", "placa": "RST012", "precio": 10834645 },
    { "marca": "Auteco", "modelo": "Xpulse", "cilindraje": 209, "color": ["negro"], "Combustible": "extra", "placa": "OPQ789", "precio": 18739519 },
    { "marca": "Motos Honda", "modelo": "YZF-R", "cilindraje": 604, "color": ["negro", "gris"], "Combustible": "corriente", "placa": "QRS345", "precio": 15285848 },
    { "marca": "TVS", "modelo": "25 NKD", "cilindraje": 690, "color": ["negro"], "Combustible": "super", "placa": "NOP012", "precio": 8979636 },
    { "marca": "Motos Suzuki", "modelo": "CB 125", "cilindraje": 938, "color": ["rojo y azul"], "Combustible": "corriente", "placa": "GHI789", "precio": 6944853 },
    { "marca": "Auteco", "modelo": "NMAX", "cilindraje": 623, "color": ["plateado"], "Combustible": "extra", "placa": "345QRS", "precio": 7059734 },
    { "marca": "Motos Yamaha", "modelo": "Dominar", "cilindraje": 361, "color": ["verde"], "Combustible": "super", "placa": "789KLM", "precio": 12544425 },
    { "marca": "AKT", "modelo": "-Strom", "cilindraje": 397, "color": ["rojo y azul", "Turquesa"], "Combustible": "super", "placa": "NOP012", "precio": 16870530 },
    { "marca": "Auteco", "modelo": "-Strom", "cilindraje": 433, "color": ["rojo y azul", "naranja", "blanco"], "Combustible": "corriente", "placa": "STU901", "precio": 18951652 },
    { "marca": "Auteco", "modelo": "Apache", "cilindraje": 751, "color": ["negro", "gris", "Turquesa"], "Combustible": "extra", "placa": "789OPQ", "precio": 18470018 },
    { "marca": "Hero", "modelo": "Ntorq", "cilindraje": 237, "color": ["blanco", "Turquesa", "Marrón"], "Combustible": "super", "placa": "890FGH", "precio": 16566865 },
    { "marca": "Motos Honda", "modelo": "Agility", "cilindraje": 695, "color": ["plateado", "gris"], "Combustible": "corriente", "placa": "JKL012", "precio": 13590856 },
    { "marca": "Royal Enfield", "modelo": "Classic", "cilindraje": 967, "color": ["Marrón", "blanco"], "Combustible": "super", "placa": "IJK123", "precio": 12782710 },
    { "marca": "Royal Enfield", "modelo": "Intercept", "cilindraje": 142, "color": ["blanco", "plateado", "Marrón"], "Combustible": "extra", "placa": "OPQ789", "precio": 18128604 },
    { "marca": "Motos Honda", "modelo": "250 Adventure", "cilindraje": 392, "color": ["negro"], "Combustible": "extra", "placa": "456LMN", "precio": 17783184 },
    { "marca": "Motos Yamaha", "modelo": "YZF-R", "cilindraje": 176, "color": ["Turquesa", "Marrón", "blanco"], "Combustible": "extra", "placa": "456LMN", "precio": 8275098 },
    { "marca": "Hero", "modelo": "Ntorq", "cilindraje": 645, "color": ["blanco"], "Combustible": "extra", "placa": "890FGH", "precio": 18680840 },
    { "marca": "Auteco", "modelo": "25 NKD", "cilindraje": 746, "color": ["gris"], "Combustible": "corriente", "placa": "VWX234", "precio": 18224965 },
    { "marca": "AKT", "modelo": "Intercept", "cilindraje": 600, "color": ["naranja", "blanco"], "Combustible": "super", "placa": "012NOP", "precio": 16991445 },
    { "marca": "Auteco", "modelo": "Xpulse", "cilindraje": 718, "color": ["amarillo", "blanco", "gris"], "Combustible": "super", "placa": "901WXY", "precio": 7823045 },
    { "marca": "Hero", "modelo": "CB 125", "cilindraje": 948, "color": ["blanco", "plateado", "rojo y azul"], "Combustible": "super", "placa": "234VWX", "precio": 8372539 },
    { "marca": "Royal Enfield", "modelo": "NMAX", "cilindraje": 524, "color": ["blanco", "negro"], "Combustible": "extra", "placa": "JKL012", "precio": 10479293 },
    { "marca": "AKT", "modelo": "Xpulse", "cilindraje": 215, "color": ["rojo y azul"], "Combustible": "corriente", "placa": "ZAB234", "precio": 7624207 },
    { "marca": "AKT", "modelo": "Dominar", "cilindraje": 138, "color": ["Turquesa"], "Combustible": "super", "placa": "ABC123", "precio": 19397040 },
    { "marca": "TVS", "modelo": "NMAX", "cilindraje": 553, "color": ["Marrón", "Turquesa", "rojo y azul"], "Combustible": "corriente", "placa": "MNO345", "precio": 13494171 },
    { "marca": "Hero", "modelo": "Apache", "cilindraje": 376, "color": ["plateado"], "Combustible": "corriente", "placa": "012JKL", "precio": 16097747 },
    { "marca": "Motos Honda", "modelo": "NMAX", "cilindraje": 405, "color": ["gris", "plateado"], "Combustible": "corriente", "placa": "890BCD", "precio": 15139067 },
    { "marca": "Royal Enfield", "modelo": "Classic", "cilindraje": 424, "color": ["rojo y azul", "naranja", "gris"], "Combustible": "super", "placa": "JKL012", "precio": 7333078 },
    { "marca": "Motos Honda", "modelo": "-Strom", "cilindraje": 469, "color": ["blanco", "Turquesa"], "Combustible": "super", "placa": "BCD890", "precio": 11461277 },
    { "marca": "Motos Suzuki", "modelo": "250 Adventure", "cilindraje": 112, "color": ["negro", "amarillo", "Turquesa"], "Combustible": "extra", "placa": "012RST", "precio": 16735192 },
    { "marca": "Motos Yamaha", "modelo": "Ntorq", "cilindraje": 842, "color": ["verde", "gris"], "Combustible": "corriente", "placa": "XYZ678", "precio": 15703832 },
    { "marca": "AKT", "modelo": "Intercept", "cilindraje": 410, "color": ["blanco"], "Combustible": "corriente", "placa": "BCD890", "precio": 6922405 },
    { "marca": "Motos Yamaha", "modelo": "-Strom", "cilindraje": 999, "color": ["plateado", "gris"], "Combustible": "corriente", "placa": "123EFG", "precio": 8820439 },
    { "marca": "AKT", "modelo": "Splendor", "cilindraje": 316, "color": ["naranja", "Turquesa", "negro"], "Combustible": "super", "placa": "789KLM", "precio": 16239930 },
    { "marca": "AKT", "modelo": "NMAX", "cilindraje": 987, "color": ["plateado", "Turquesa"], "Combustible": "corriente", "placa": "FGH890", "precio": 14432291 },
    { "marca": "Royal Enfield", "modelo": "Classic", "cilindraje": 934, "color": ["rojo y azul", "naranja"], "Combustible": "super", "placa": "345QRS", "precio": 5746393 },
    { "marca": "Motos Suzuki", "modelo": "Apache", "cilindraje": 382, "color": ["negro", "amarillo"], "Combustible": "extra", "placa": "345MNO", "precio": 17365142 },
    { "marca": "Motos Honda", "modelo": "Splendor", "cilindraje": 427, "color": ["Marrón", "naranja", "gris"], "Combustible": "corriente", "placa": "678PQR", "precio": 9528022 },
    { "marca": "AKT", "modelo": "Intercept", "cilindraje": 644, "color": ["amarillo", "verde"], "Combustible": "super", "placa": "901STU", "precio": 7237741 },
    { "marca": "Royal Enfield", "modelo": "GSX-R", "cilindraje": 959, "color": ["rojo y azul", "naranja", "plateado"], "Combustible": "super", "placa": "FGH890", "precio": 9122386 },
    { "marca": "Motos Suzuki", "modelo": "Classic", "cilindraje": 946, "color": ["blanco"], "Combustible": "super", "placa": "901WXY", "precio": 10237953 },
    { "marca": "Auteco", "modelo": "CBR", "cilindraje": 989, "color": ["Marrón"], "Combustible": "extra", "placa": "OPQ789", "precio": 7560179 },
    { "marca": "Motos Honda", "modelo": "NMAX", "cilindraje": 476, "color": ["rojo y azul", "negro", "gris"], "Combustible": "corriente", "placa": "XYZ678", "precio": 5134542 },
    { "marca": "Hero", "modelo": "Intercept", "cilindraje": 904, "color": ["Marrón", "plateado"], "Combustible": "corriente", "placa": "IJK123", "precio": 6920366 },
    { "marca": "Motos Suzuki", "modelo": "NMAX", "cilindraje": 682, "color": ["gris", "amarillo"], "Combustible": "extra", "placa": "PQR678", "precio": 9078684 },
    { "marca": "Motos Suzuki", "modelo": "YZF-R", "cilindraje": 824, "color": ["Turquesa", "negro"], "Combustible": "corriente", "placa": "QRS345", "precio": 11954035 },
    { "marca": "Motos Suzuki", "modelo": "Pulsar", "cilindraje": 210, "color": ["Turquesa"], "Combustible": "extra", "placa": "LMN456", "precio": 18227038 },
    { "marca": "Hero", "modelo": "Apache", "cilindraje": 114, "color": ["verde", "gris", "Turquesa"], "Combustible": "super", "placa": "456HIJ", "precio": 9932069 },
    { "marca": "TVS", "modelo": "Classic", "cilindraje": 405, "color": ["amarillo", "naranja"], "Combustible": "extra", "placa": "789OPQ", "precio": 13175622 },
    { "marca": "AKT", "modelo": "25 NKD", "cilindraje": 119, "color": ["plateado", "Turquesa", "blanco"], "Combustible": "extra", "placa": "456DEF", "precio": 5111375 },
    { "marca": "Motos Honda", "modelo": "CBR", "cilindraje": 526, "color": ["Marrón", "verde", "Turquesa"], "Combustible": "extra", "placa": "ZAB234", "precio": 12834230 },
    { "marca": "Auteco", "modelo": "-Strom", "cilindraje": 696, "color": ["gris", "plateado", "verde"], "Combustible": "extra", "placa": "KLM789", "precio": 10463240 },
    { "marca": "Motos Yamaha", "modelo": "Splendor", "cilindraje": 693, "color": ["plateado"], "Combustible": "corriente", "placa": "789OPQ", "precio": 16208056 },
    { "marca": "AKT", "modelo": "-Strom", "cilindraje": 529, "color": ["amarillo"], "Combustible": "extra", "placa": "HIJ456", "precio": 18631983 },
    { "marca": "Hero", "modelo": "fz25", "cilindraje": 233, "color": ["blanco", "naranja"], "Combustible": "corriente", "placa": "123EFG", "precio": 8736202 },
    { "marca": "Motos Suzuki", "modelo": "Dominar", "cilindraje": 440, "color": ["Turquesa"], "Combustible": "super", "placa": "ZAB234", "precio": 10654816 },
    { "marca": "Motos Yamaha", "modelo": "Classic", "cilindraje": 975, "color": ["plateado", "Turquesa", "amarillo"], "Combustible": "corriente", "placa": "234VWX", "precio": 12212091 },
    { "marca": "Royal Enfield", "modelo": "Intercept", "cilindraje": 675, "color": ["Marrón"], "Combustible": "super", "placa": "MNO345", "precio": 8392663 },
    { "marca": "TVS", "modelo": "NMAX", "cilindraje": 291, "color": ["amarillo", "Turquesa"], "Combustible": "corriente", "placa": "890FGH", "precio": 8756235 },
    { "marca": "Auteco", "modelo": "Pulsar", "cilindraje": 667, "color": ["amarillo", "Turquesa", "negro"], "Combustible": "super", "placa": "UVW345", "precio": 19161234 },
    { "marca": "AKT", "modelo": "Classic", "cilindraje": 654, "color": ["Turquesa", "blanco", "verde"], "Combustible": "super", "placa": "BCD890", "precio": 19334755 },
    { "marca": "Motos Yamaha", "modelo": "fz25", "cilindraje": 846, "color": ["plateado", "blanco", "Turquesa"], "Combustible": "extra", "placa": "KLM789", "precio": 17940384 },
    { "marca": "Auteco", "modelo": "Pulsar", "cilindraje": 429, "color": ["amarillo", "negro"], "Combustible": "extra", "placa": "456LMN", "precio": 19912489 },
    { "marca": "Motos Yamaha", "modelo": "YZF-R", "cilindraje": 519, "color": ["verde", "plateado", "amarillo"], "Combustible": "corriente", "placa": "123EFG", "precio": 9479585 },
    { "marca": "TVS", "modelo": "GSX-R", "cilindraje": 912, "color": ["blanco"], "Combustible": "extra", "placa": "456LMN", "precio": 7905422 },
    { "marca": "Motos Yamaha", "modelo": "CBR", "cilindraje": 458, "color": ["verde", "amarillo"], "Combustible": "corriente", "placa": "WXY901", "precio": 18854357 },
    { "marca": "Auteco", "modelo": "250 Adventure", "cilindraje": 159, "color": ["rojo y azul"], "Combustible": "extra", "placa": "456LMN", "precio": 12491242 },
    { "marca": "AKT", "modelo": "250 Adventure", "cilindraje": 268, "color": ["plateado"], "Combustible": "super", "placa": "456DEF", "precio": 6073039 },
    { "marca": "Hero", "modelo": "CB 125", "cilindraje": 753, "color": ["negro", "verde"], "Combustible": "corriente", "placa": "DEF456", "precio": 6931411 },
    { "marca": "Royal Enfield", "modelo": "NMAX", "cilindraje": 731, "color": ["Marrón", "naranja", "verde"], "Combustible": "extra", "placa": "VWX234", "precio": 15608800 },
    { "marca": "Auteco", "modelo": "fz25", "cilindraje": 954, "color": ["verde", "blanco"], "Combustible": "corriente", "placa": "IJK123", "precio": 6959008 },
    { "marca": "Motos Yamaha", "modelo": "Pulsar", "cilindraje": 374, "color": ["Marrón"], "Combustible": "extra", "placa": "789KLM", "precio": 7225244 },
    { "marca": "AKT", "modelo": "Intercept", "cilindraje": 308, "color": ["amarillo", "negro", "Marrón"], "Combustible": "extra", "placa": "EFG123", "precio": 14334921 },
    { "marca": "Royal Enfield", "modelo": "Classic", "cilindraje": 776, "color": ["Turquesa", "naranja", "blanco"], "Combustible": "super", "placa": "UVW345", "precio": 12620140 },
    { "marca": "Motos Yamaha", "modelo": "Splendor", "cilindraje": 645, "color": ["plateado"], "Combustible": "super", "placa": "567YZA", "precio": 15852301 },
    { "marca": "Auteco", "modelo": "Dominar", "cilindraje": 488, "color": ["verde", "Marrón"], "Combustible": "super", "placa": "QRS345", "precio": 16985110 },
    { "marca": "Motos Honda", "modelo": "Pulsar", "cilindraje": 422, "color": ["amarillo", "Turquesa"], "Combustible": "extra", "placa": "890BCD", "precio": 10907351 },
    { "marca": "Motos Honda", "modelo": "Ntorq", "cilindraje": 649, "color": ["plateado", "rojo y azul"], "Combustible": "corriente", "placa": "UVW345", "precio": 9073824 },
    { "marca": "AKT", "modelo": "Pulsar", "cilindraje": 880, "color": ["amarillo", "Turquesa", "plateado"], "Combustible": "corriente", "placa": "123ABC", "precio": 11722921 },
    { "marca": "Hero", "modelo": "-Strom", "cilindraje": 476, "color": ["verde"], "Combustible": "extra", "placa": "789GHI", "precio": 18475256 },
    { "marca": "Motos Yamaha", "modelo": "25 NKD", "cilindraje": 402, "color": ["gris", "negro", "plateado"], "Combustible": "corriente", "placa": "KLM789", "precio": 7712067 },
    { "marca": "Motos Honda", "modelo": "Intercept", "cilindraje": 530, "color": ["verde", "naranja", "blanco"], "Combustible": "extra", "placa": "VWX234", "precio": 6937387 },
    { "marca": "Motos Honda", "modelo": "Intercept", "cilindraje": 994, "color": ["Marrón", "amarillo", "naranja"], "Combustible": "super", "placa": "WXY901", "precio": 19959015 },
    { "marca": "Auteco", "modelo": "Ntorq", "cilindraje": 564, "color": ["amarillo"], "Combustible": "super", "placa": "DEF456", "precio": 14614668 },
    { "marca": "TVS", "modelo": "Xpulse", "cilindraje": 520, "color": ["Marrón", "gris", "Turquesa"], "Combustible": "corriente", "placa": "012NOP", "precio": 19728017 },
    { "marca": "TVS", "modelo": "Africa Twin", "cilindraje": 706, "color": ["plateado", "Marrón"], "Combustible": "corriente", "placa": "HIJ456", "precio": 7401488 },
    { "marca": "Motos Yamaha", "modelo": "CB 125", "cilindraje": 874, "color": ["rojo y azul", "naranja", "amarillo"], "Combustible": "corriente", "placa": "567CDE", "precio": 9403833 },
    { "marca": "Motos Yamaha", "modelo": "Agility", "cilindraje": 737, "color": ["Marrón"], "Combustible": "super", "placa": "DEF456", "precio": 19888223 },
    { "marca": "Motos Yamaha", "modelo": "NMAX", "cilindraje": 347, "color": ["plateado"], "Combustible": "extra", "placa": "WXY901", "precio": 18775438 },
    { "marca": "Auteco", "modelo": "Classic", "cilindraje": 379, "color": ["gris"], "Combustible": "corriente", "placa": "012NOP", "precio": 10082144 },
    { "marca": "AKT", "modelo": "Splendor", "cilindraje": 289, "color": ["verde"], "Combustible": "super", "placa": "012NOP", "precio": 16954223 },
    { "marca": "Motos Yamaha", "modelo": "Apache", "cilindraje": 839, "color": ["plateado", "blanco"], "Combustible": "corriente", "placa": "123EFG", "precio": 10426960 },
    { "marca": "TVS", "modelo": "CB 125", "cilindraje": 504, "color": ["gris", "rojo y azul"], "Combustible": "extra", "placa": "ABC123", "precio": 10590548 },
    { "marca": "TVS", "modelo": "Classic", "cilindraje": 226, "color": ["verde", "plateado"], "Combustible": "corriente", "placa": "DEF456", "precio": 19545361 },
    { "marca": "Royal Enfield", "modelo": "CBR", "cilindraje": 401, "color": ["blanco", "gris"], "Combustible": "corriente", "placa": "890FGH", "precio": 6900210 },
    { "marca": "AKT", "modelo": "Apache", "cilindraje": 715, "color": ["Marrón", "naranja"], "Combustible": "super", "placa": "901STU", "precio": 14376521 },
    { "marca": "Royal Enfield", "modelo": "Pulsar", "cilindraje": 840, "color": ["amarillo", "gris", "plateado"], "Combustible": "corriente", "placa": "456HIJ", "precio": 18887675 },
    { "marca": "Hero", "modelo": "Xpulse", "cilindraje": 680, "color": ["plateado"], "Combustible": "corriente", "placa": "DEF456", "precio": 8669795 },
    { "marca": "TVS", "modelo": "CBR", "cilindraje": 940, "color": ["amarillo", "naranja"], "Combustible": "super", "placa": "TUV678", "precio": 7186467 },
    { "marca": "TVS", "modelo": "Apache", "cilindraje": 836, "color": ["plateado"], "Combustible": "super", "placa": "ABC123", "precio": 11282956 },
    { "marca": "Auteco", "modelo": "CBR", "cilindraje": 372, "color": ["Turquesa", "verde"], "Combustible": "super", "placa": "BCD890", "precio": 15131624 },
    { "marca": "Motos Suzuki", "modelo": "fz25", "cilindraje": 488, "color": ["gris", "plateado", "verde"], "Combustible": "corriente", "placa": "789OPQ", "precio": 19282446 },
    { "marca": "Hero", "modelo": "-Strom", "cilindraje": 220, "color": ["verde", "amarillo", "rojo y azul"], "Combustible": "extra", "placa": "789KLM", "precio": 12472494 },
    { "marca": "Motos Suzuki", "modelo": "YZF-R", "cilindraje": 760, "color": ["verde", "naranja"], "Combustible": "extra", "placa": "JKL012", "precio": 12350243 },
    { "marca": "Auteco", "modelo": "-Strom", "cilindraje": 342, "color": ["verde"], "Combustible": "extra", "placa": "012NOP", "precio": 11985890 },
    { "marca": "Motos Honda", "modelo": "CBR", "cilindraje": 453, "color": ["gris", "verde", "naranja"], "Combustible": "extra", "placa": "QRS345", "precio": 5356683 },
    { "marca": "TVS", "modelo": "25 NKD", "cilindraje": 647, "color": ["Marrón"], "Combustible": "corriente", "placa": "234VWX", "precio": 16302655 },
    { "marca": "TVS", "modelo": "Xpulse", "cilindraje": 921, "color": ["amarillo", "verde", "naranja"], "Combustible": "super", "placa": "YZA567", "precio": 13924994 },
    { "marca": "Hero", "modelo": "fz25", "cilindraje": 516, "color": ["gris", "plateado"], "Combustible": "corriente", "placa": "XYZ678", "precio": 8655378 },
    { "marca": "TVS", "modelo": "Apache", "cilindraje": 862, "color": ["naranja", "rojo y azul"], "Combustible": "extra", "placa": "YZA567", "precio": 9893163 },
    { "marca": "Auteco", "modelo": "Classic", "cilindraje": 339, "color": ["naranja"], "Combustible": "extra", "placa": "WXY901", "precio": 11007182 },
    { "marca": "TVS", "modelo": "CBR", "cilindraje": 304, "color": ["rojo y azul", "blanco", "amarillo"], "Combustible": "super", "placa": "234ZAB", "precio": 9632966 },
    { "marca": "Hero", "modelo": "GSX-R", "cilindraje": 443, "color": ["rojo y azul"], "Combustible": "corriente", "placa": "ABC123", "precio": 19041504 },
    { "marca": "Motos Suzuki", "modelo": "Xpulse", "cilindraje": 144, "color": ["Marrón", "gris", "Turquesa"], "Combustible": "extra", "placa": "456HIJ", "precio": 16189634 },
    { "marca": "AKT", "modelo": "Splendor", "cilindraje": 324, "color": ["rojo y azul", "blanco", "gris"], "Combustible": "corriente", "placa": "678PQR", "precio": 18211586 },
    { "marca": "TVS", "modelo": "CB 125", "cilindraje": 849, "color": ["verde"], "Combustible": "corriente", "placa": "789OPQ", "precio": 11098739 },
    { "marca": "TVS", "modelo": "Ntorq", "cilindraje": 302, "color": ["naranja", "Turquesa", "blanco"], "Combustible": "super", "placa": "UVW345", "precio": 12967510 },
    { "marca": "Motos Suzuki", "modelo": "fz25", "cilindraje": 619, "color": ["verde"], "Combustible": "corriente", "placa": "890BCD", "precio": 18441700 },
    { "marca": "Royal Enfield", "modelo": "fz25", "cilindraje": 740, "color": ["verde"], "Combustible": "corriente", "placa": "CDE567", "precio": 5706301 },
    { "marca": "Hero", "modelo": "Apache", "cilindraje": 617, "color": ["verde"], "Combustible": "extra", "placa": "567YZA", "precio": 5355558 },
    { "marca": "Motos Honda", "modelo": "NMAX", "cilindraje": 570, "color": ["amarillo", "Marrón", "plateado"], "Combustible": "extra", "placa": "456LMN", "precio": 18374547 },
    { "marca": "AKT", "modelo": "-Strom", "cilindraje": 203, "color": ["blanco", "amarillo", "rojo y azul"], "Combustible": "super", "placa": "TUV678", "precio": 6979430 },
    { "marca": "Hero", "modelo": "fz25", "cilindraje": 797, "color": ["negro", "gris"], "Combustible": "corriente", "placa": "RST012", "precio": 12385809 },
    { "marca": "Auteco", "modelo": "Pulsar", "cilindraje": 454, "color": ["plateado", "Turquesa", "rojo y azul"], "Combustible": "extra", "placa": "456DEF", "precio": 12047150 },
    { "marca": "Royal Enfield", "modelo": "Xpulse", "cilindraje": 123, "color": ["rojo y azul", "plateado"], "Combustible": "corriente", "placa": "890FGH", "precio": 13937222 },
    { "marca": "Motos Suzuki", "modelo": "-Strom", "cilindraje": 133, "color": ["negro", "gris"], "Combustible": "super", "placa": "901STU", "precio": 11578159 },
    { "marca": "Royal Enfield", "modelo": "fz25", "cilindraje": 632, "color": ["gris"], "Combustible": "corriente", "placa": "BCD890", "precio": 10513402 },
    { "marca": "Hero", "modelo": "25 NKD", "cilindraje": 505, "color": ["Marrón", "rojo y azul"], "Combustible": "extra", "placa": "789GHI", "precio": 5065451 },
    { "marca": "Royal Enfield", "modelo": "YZF-R", "cilindraje": 133, "color": ["blanco"], "Combustible": "extra", "placa": "DEF456", "precio": 13412231 },
    { "marca": "Auteco", "modelo": "NMAX", "cilindraje": 689, "color": ["amarillo", "verde"], "Combustible": "extra", "placa": "DEF456", "precio": 4717599 },
    { "marca": "Motos Yamaha", "modelo": "Classic", "cilindraje": 439, "color": ["gris"], "Combustible": "extra", "placa": "QRS345", "precio": 13072673 },
    { "marca": "Motos Honda", "modelo": "25 NKD", "cilindraje": 555, "color": ["Marrón", "amarillo"], "Combustible": "extra", "placa": "RST012", "precio": 4979900 },
    { "marca": "Auteco", "modelo": "Intercept", "cilindraje": 295, "color": ["rojo y azul"], "Combustible": "corriente", "placa": "OPQ789", "precio": 7750305 },
    { "marca": "Hero", "modelo": "Dominar", "cilindraje": 571, "color": ["naranja"], "Combustible": "corriente", "placa": "JKL012", "precio": 10472417 },
    { "marca": "AKT", "modelo": "GSX-R", "cilindraje": 225, "color": ["amarillo"], "Combustible": "corriente", "placa": "KLM789", "precio": 14373033 },
    { "marca": "Auteco", "modelo": "Classic", "cilindraje": 810, "color": ["Marrón", "plateado"], "Combustible": "super", "placa": "012NOP", "precio": 10532659 },
    { "marca": "Auteco", "modelo": "-Strom", "cilindraje": 959, "color": ["verde", "Turquesa", "plateado"], "Combustible": "corriente", "placa": "HIJ456", "precio": 9450263 },
    { "marca": "TVS", "modelo": "Ntorq", "cilindraje": 734, "color": ["rojo y azul"], "Combustible": "extra", "placa": "STU901", "precio": 11369548 },
    { "marca": "Royal Enfield", "modelo": "Dominar", "cilindraje": 888, "color": ["plateado", "Marrón"], "Combustible": "corriente", "placa": "YZA567", "precio": 10764699 },
    { "marca": "Motos Honda", "modelo": "-Strom", "cilindraje": 675, "color": ["Turquesa", "negro"], "Combustible": "super", "placa": "456DEF", "precio": 14950689 },
    { "marca": "Motos Honda", "modelo": "Dominar", "cilindraje": 829, "color": ["negro", "gris", "rojo y azul"], "Combustible": "extra", "placa": "OPQ789", "precio": 6229257 },
    { "marca": "Hero", "modelo": "NMAX", "cilindraje": 303, "color": ["rojo y azul", "plateado", "negro"], "Combustible": "corriente", "placa": "KLM789", "precio": 12112708 },
    { "marca": "AKT", "modelo": "fz25", "cilindraje": 741, "color": ["amarillo", "verde", "plateado"], "Combustible": "extra", "placa": "012JKL", "precio": 11370749 },
    { "marca": "Hero", "modelo": "Ntorq", "cilindraje": 511, "color": ["amarillo"], "Combustible": "corriente", "placa": "UVW345", "precio": 8339788 },
    { "marca": "AKT", "modelo": "Apache", "cilindraje": 777, "color": ["rojo y azul", "naranja", "negro"], "Combustible": "extra", "placa": "012NOP", "precio": 19975064 },
    { "marca": "Motos Honda", "modelo": "YZF-R", "cilindraje": 455, "color": ["rojo y azul"], "Combustible": "corriente", "placa": "123EFG", "precio": 14738725 },
    { "marca": "TVS", "modelo": "Africa Twin", "cilindraje": 441, "color": ["gris"], "Combustible": "corriente", "placa": "JKL012", "precio": 12812995 },
    { "marca": "Motos Honda", "modelo": "Agility", "cilindraje": 527, "color": ["plateado", "blanco", "amarillo"], "Combustible": "super", "placa": "456LMN", "precio": 14678619 },
    { "marca": "AKT", "modelo": "Splendor", "cilindraje": 834, "color": ["negro"], "Combustible": "extra", "placa": "GHI789", "precio": 8457882 },
    { "marca": "Motos Yamaha", "modelo": "250 Adventure", "cilindraje": 862, "color": ["blanco"], "Combustible": "corriente", "placa": "678PQR", "precio": 13721139 },
    { "marca": "Auteco", "modelo": "YZF-R", "cilindraje": 551, "color": ["verde", "blanco"], "Combustible": "super", "placa": "RST012", "precio": 4689405 },
    { "marca": "Motos Honda", "modelo": "250 Adventure", "cilindraje": 470, "color": ["amarillo", "rojo y azul", "negro"], "Combustible": "extra", "placa": "567CDE", "precio": 15058469 },
    { "marca": "Hero", "modelo": "fz25", "cilindraje": 541, "color": ["naranja", "gris"], "Combustible": "extra", "placa": "901WXY", "precio": 10952496 },
    { "marca": "Auteco", "modelo": "Dominar", "cilindraje": 712, "color": ["negro"], "Combustible": "corriente", "placa": "KLM789", "precio": 5864578 },
    { "marca": "Hero", "modelo": "Dominar", "cilindraje": 595, "color": ["verde", "Turquesa", "gris"], "Combustible": "extra", "placa": "345MNO", "precio": 8609027 },
    { "marca": "Auteco", "modelo": "Dominar", "cilindraje": 103, "color": ["blanco", "amarillo", "gris"], "Combustible": "corriente", "placa": "123EFG", "precio": 6627079 },
    { "marca": "TVS", "modelo": "Intercept", "cilindraje": 246, "color": ["negro"], "Combustible": "extra", "placa": "890BCD", "precio": 16985062 },
    { "marca": "Hero", "modelo": "Intercept", "cilindraje": 686, "color": ["verde", "Marrón", "negro"], "Combustible": "super", "placa": "EFG123", "precio": 11148778 },
    { "marca": "Royal Enfield", "modelo": "CB 125", "cilindraje": 128, "color": ["amarillo", "naranja", "Turquesa"], "Combustible": "super", "placa": "234VWX", "precio": 9658274 },
    { "marca": "TVS", "modelo": "Classic", "cilindraje": 808, "color": ["Marrón", "naranja"], "Combustible": "super", "placa": "YZA567", "precio": 18525261 },
    { "marca": "Hero", "modelo": "fz25", "cilindraje": 886, "color": ["blanco"], "Combustible": "super", "placa": "123ABC", "precio": 10765884 },
    { "marca": "Auteco", "modelo": "25 NKD", "cilindraje": 145, "color": ["plateado", "negro", "amarillo"], "Combustible": "corriente", "placa": "MNO345", "precio": 18693846 },
    { "marca": "Royal Enfield", "modelo": "-Strom", "cilindraje": 880, "color": ["amarillo"], "Combustible": "extra", "placa": "UVW345", "precio": 19041491 }]
);